# Generated by Django 5.2.15 on 2026-06-17 13:28

import apps.core.managers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ledger', '0002_accountperiodbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=50)),
                ('contract_date', models.DateField()),
                ('contract_type', models.CharField(choices=[('sale', 'Hợp đồng mua bán'), ('purchase', 'Hợp đồng mua hàng'), ('service', 'Hợp đồng cung cấp dịch vụ'), ('construction', 'Hợp đồng thi công'), ('labor', 'Hợp đồng lao động'), ('lease', 'Hợp đồng thuê'), ('other', 'Khác')], default='other', max_length=20)),
                ('party_code', models.CharField(blank=True, default='', max_length=50)),
                ('party_name', models.CharField(max_length=255)),
                ('party_tax_code', models.CharField(blank=True, default='', max_length=20)),
                ('party_address', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Dự thảo'), ('active', 'Đang hiệu lực'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='draft', max_length=20)),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('linked_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='ledger.accountingvoucher')),
            ],
            options={
                'db_table': 'contract',
                'ordering': ['-contract_date', '-id'],
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_no', models.CharField(max_length=50)),
                ('minutes_date', models.DateField()),
                ('minutes_type', models.CharField(choices=[('handover', 'Biên bản bàn giao'), ('acceptance', 'Biên bản nghiệm thu'), ('inventory', 'Biên bản kiểm kê'), ('liquidation', 'Biên bản thanh lý'), ('reconciliation', 'Biên bản đối chiếu'), ('adjustment', 'Biên bản điều chỉnh'), ('other', 'Biên bản khác')], default='other', max_length=20)),
                ('party_code', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='minutes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutes_set', to='contracts.contract')),
                ('linked_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes', to='ledger.accountingvoucher')),
            ],
            options={
                'db_table': 'minutes',
                'ordering': ['-minutes_date', '-id'],
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['company', 'contract_type'], name='contract_company_078cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['company', 'status'], name='contract_company_f47abe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('company', 'contract_no')},
        ),
        migrations.AddIndex(
            model_name='minutes',
            index=models.Index(fields=['company', 'minutes_type'], name='minutes_company_abe3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='minutes',
            index=models.Index(fields=['company', 'minutes_date'], name='minutes_company_e76dbb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='minutes',
            unique_together={('company', 'minutes_no')},
        ),
    ]
