# Generated by Django 5.2.15 on 2026-06-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contract_type', models.CharField(max_length=20)),
                ('template_html', models.TextField()),
                ('required_fields', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('legal_basis', models.TextField(blank=True, default='')),
                ('version', models.CharField(default='2026', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contract_template',
                'ordering': ['code'],
            },
        ),
    ]
