# Generated by Django 5.2.15 on 2026-06-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contracttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('sale', 'Hợp đồng mua bán'), ('purchase', 'Hợp đồng mua hàng'), ('service', 'Hợp đồng cung cấp dịch vụ'), ('construction', 'Hợp đồng thi công'), ('labor', 'Hợp đồng lao động'), ('lease', 'Hợp đồng thuê'), ('bidding_lump_sum', 'Hợp đồng đấu thầu trọn gói'), ('bidding_unit_price', 'Hợp đồng đấu thầu đơn giá điều chỉnh'), ('bidding_consulting', 'Hợp đồng tư vấn đấu thầu'), ('other', 'Khác')], default='other', max_length=20),
        ),
    ]
