# Generated by Django 5.2.15 on 2026-07-16 02:30

import apps.core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_contracttemplate_company"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contracttemplate",
            managers=[
                ("objects", apps.core.managers.CompanyManager()),
            ],
        ),
    ]
