# Generated by Django 5.2.15 on 2026-07-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0006_dnsn_models"),
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseinvoice",
            name="dnsn_voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_invoices",
                to="ledger.dnsnvoucher",
            ),
        ),
    ]
