# Generated by Django 5.2.15 on 2026-06-17 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ledger', '0002_accountperiodbalance'),
        ('master_data', '0005_product_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('invoice_type', models.CharField(choices=[('goods', 'Hàng hóa'), ('service', 'Dịch vụ'), ('export', 'Xuất khẩu')], default='goods', max_length=20)),
                ('sales_staff_code', models.CharField(blank=True, default='', max_length=50)),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('vat_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('paid_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(0, 'Chưa thanh toán'), (1, 'Thanh toán một phần'), (2, 'Đã thanh toán')], default=0)),
                ('status', models.PositiveSmallIntegerField(default=2, help_text='0=Draft, 1=Subsidiary, 2=Ledger, 3=Locked')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='master_data.customer')),
                ('gl_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='ledger.accountingvoucher')),
            ],
            options={
                'db_table': 'sales_invoice',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_id', models.CharField(default='CAI', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('discount_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('amount_before_vat', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=6)),
                ('vat_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('revenue_account', models.CharField(default='5111', max_length=20)),
                ('vat_account', models.CharField(default='33311', max_length=20)),
                ('inventory_account', models.CharField(blank=True, default='', max_length=20)),
                ('cost_account', models.CharField(default='632', max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_lines', to='master_data.product')),
            ],
            options={
                'db_table': 'sales_invoice_line',
                'ordering': ['line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'invoice_date'], name='sales_invoi_company_68df40_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['customer', 'invoice_date'], name='sales_invoi_custome_0818e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoice',
            unique_together={('company', 'invoice_type', 'invoice_no')},
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoiceline',
            unique_together={('invoice', 'line_no')},
        ),
    ]
