# Generated by Django 5.2.15 on 2026-06-18 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_pit_history_and_bidding'),
        ('core', '0007_alter_taxrateconfig_pit_dependent_deduction_and_more'),
        ('hr', '0003_leaverecord_insurancecontribution_leavebalance'),
        ('master_data', '0005_product_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('customer_code', models.CharField(blank=True, default='', max_length=50)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('budget_revenue', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('budget_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('planned', 'Lập kế hoạch'), ('active', 'Đang thực hiện'), ('on_hold', 'Tạm dừng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='planned', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('critical', 'Khẩn cấp')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.company')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='contracts.contract')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='hr.employee')),
            ],
            options={
                'db_table': 'project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('budget_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('not_started', 'Chưa bắt đầu'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('blocked', 'Bị chặn')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project')),
            ],
            options={
                'db_table': 'project_phase',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('human', 'Nhân sự'), ('material', 'Vật tư/Thiết bị'), ('equipment', 'Thiết bị/Máy móc'), ('service', 'Dịch vụ ngoài')], max_length=20)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('planned_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('actual_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('assigned_from', models.DateField(blank=True, null=True)),
                ('assigned_to', models.DateField(blank=True, null=True)),
                ('utilization', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assignments', to='hr.employee')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='projects.projectphase')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_usages', to='master_data.product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.project')),
            ],
            options={
                'db_table': 'project_resource',
                'ordering': ['resource_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('revenue', 'Doanh thu'), ('material_cost', 'Chi phí vật tư'), ('labor_cost', 'Chi phí nhân công'), ('overhead', 'Chi phí chung'), ('other', 'Khác')], max_length=20)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('description', models.TextField(blank=True, default='')),
                ('sales_invoice_id', models.BigIntegerField(blank=True, null=True)),
                ('purchase_invoice_id', models.BigIntegerField(blank=True, null=True)),
                ('voucher_id', models.BigIntegerField(blank=True, null=True)),
                ('payroll_line_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='projects.project')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectresource')),
            ],
            options={
                'db_table': 'project_transaction',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'status'], name='project_company_276e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'manager'], name='project_company_160dce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='projectphase',
            unique_together={('project', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='projecttransaction',
            index=models.Index(fields=['project', 'transaction_type'], name='project_tra_project_61fef6_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttransaction',
            index=models.Index(fields=['transaction_date'], name='project_tra_transac_f8b7ab_idx'),
        ),
    ]
