# Generated by Django 5.2.15 on 2026-06-22 17:22

import apps.core.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_pit_history_and_bidding'),
        ('core', '0007_alter_taxrateconfig_pit_dependent_deduction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_no', models.CharField(max_length=50)),
                ('bid_name', models.CharField(max_length=500)),
                ('investor_name', models.CharField(max_length=255)),
                ('investor_tax_code', models.CharField(blank=True, default='', max_length=20)),
                ('bid_method', models.CharField(choices=[('open', 'Đấu thầu rộng rãi'), ('limited', 'Đấu thầu hạn chế'), ('direct', 'Chỉ định thầu'), ('self_performed', 'Tự thực hiện'), ('community', 'Đấu thầu cộng đồng')], default='open', max_length=20)),
                ('bid_form', models.CharField(choices=[('one_stage', 'Một giai đoạn một túi hồ sơ'), ('1s2e', 'Một giai đoạn hai túi hồ sơ'), ('two_stage', 'Hai giai đoạn một túi hồ sơ')], default='one_stage', max_length=20)),
                ('bid_type', models.CharField(default=' construction', max_length=30)),
                ('bid_package_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('duration_days', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('bid_submission_deadline', models.DateTimeField(blank=True, null=True)),
                ('bid_opening_at', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=True)),
                ('bid_system_ref', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='identified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bid_opportunity',
                'ordering': ['-bid_submission_deadline', '-id'],
                'unique_together': {('company', 'bid_no')},
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='BidDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ifb', 'Hồ sơ mời thầu (HSMT)'), ('proposal', 'Hồ sơ dự thầu (HSDT)'), ('technical', 'Đề xuất kỹ thuật'), ('financial', 'Đề xuất tài chính'), ('contract_draft', 'Dự thảo hợp đồng'), ('other', 'Khác')], default='proposal', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='bidding/docs/')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bidding.bidopportunity')),
            ],
            options={
                'db_table': 'bid_document',
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='BidResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('won', 'Trúng thầu'), ('lost', 'Trượt thầu'), ('cancelled', 'Hủy bỏ'), ('waiting', 'Chờ kết quả')], default='waiting', max_length=20)),
                ('awarded_at', models.DateField(blank=True, null=True)),
                ('final_contract_value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('winner_name', models.CharField(blank=True, default='', max_length=255)),
                ('loss_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='bidding.bidopportunity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_results', to='contracts.contract')),
            ],
            options={
                'db_table': 'bid_result',
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='BidSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('bid_security_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('bid_security_provider', models.CharField(blank=True, default='', max_length=100)),
                ('proposed_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('proposed_duration_days', models.PositiveIntegerField(default=0)),
                ('proposed_technical_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='bidding.bidopportunity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bid_submission',
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='MAIN', max_length=30)),
                ('name', models.CharField(default='', max_length=255)),
                ('legal_representative', models.CharField(blank=True, default='', max_length=255)),
                ('tax_code', models.CharField(blank=True, default='', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('capability_level', models.CharField(choices=[('I', 'Hạng I'), ('II', 'Hạng II'), ('III', 'Hạng III'), ('X', 'Chưa xếp hạng')], default='X', max_length=5)),
                ('fields_of_activity', models.TextField(blank=True, default='')),
                ('years_in_business', models.PositiveSmallIntegerField(default=0)),
                ('financial_capacity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('staff_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'db_table': 'contractor_profile',
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
    ]
