from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (
    AccountCreateView,
    AdminRoleEditView,
    AdminRoleListView,
    AdminUserAssignView,
    AdminUserListView,
    MyPermissionsView,
    ApprovalApproveView,
    ApprovalDetailView,
    ApprovalQueueView,
    ApprovalRejectView,
    ApprovalRuleListView,
    EInvoiceCancelView,
    EInvoiceDetailView,
    EInvoiceIssueFromSalesView,
    EInvoiceJsonDownloadView,
    EInvoiceListView,
    EInvoicePublishView,
    EInvoiceReportView,
    EInvoiceXmlDownloadView,
    # Banking + guarantees + loans (P1)
    BankAccountListView,
    BankReconciliationRunView,
    BankReconciliationView,
    CompanyProfileView,
    ContactListAdminView,
    BankStatementImportDetailView,
    BankStatementImportListView,
    BankStatementUploadView,
    BankGuaranteeListView,
    BankLoanListView,
    BidConvertToContractView,
    BidOpportunityDetailView,
    BidOpportunityListView,
    BudgetDetailView,
    BudgetGenerateView,
    BudgetListView,
    BudgetRefreshActualsView,
    CashFlowGenerateView,
    CashFlowView,
    ExchangeRateListView,
    FxRevaluationListView,
    FxRevaluationRunView,
    AssetCreateView,
    AssetDisposeView,
    AssetListView,
    AssetTransactionListView,
    AssetTransferView,
    AttachmentDeleteView,
    AttachmentDownloadView,
    AttachmentUploadView,
    BalanceSheetView,
    CampaignCreateView,
    CampaignListView,
    CashPaymentCreateView,
    CashReceiptCreateView,
    ChartOfAccountsListView,
    ContractCreateView,
    ContractDetailView,
    ContractExportDocxView,
    ContractGenerateView,
    ContractListView,
    ContractTemplateListView,
    ContractTemplateCreateView,
    ContractTemplateEditView,
    ContractTemplateDeleteView,
    ContractTemplatePreviewRawView,
    CustomerCreateView,
    CustomerDeleteView,
    CustomerExportView,
    CustomerListView,
    CustomerUpdateView,
    D62ReportView,
    DashboardView,
    QuickExpenseView,
    DependentListView,
    DepreciationRunView,
    DocumentDeleteView,
    DocumentDownloadView,
    EmployeeCreateView,
    EmployeeListView,
    GeneralJournalView,
    GeneralLedgerView,
    InputInvoiceListView,
    InputInvoiceProcessView,
    InputInvoiceUploadView,
    InsuranceDashboardView,
    LaborContractCreateView,
    LaborContractListView,
    LaborUsageReportView,
    LeadCreateView,
    LeadListView,
    LeaveRequestView,
    OpportunityConvertView,
    OpportunityCreateView,
    OpportunityDetailView,
    OpportunityListView,
    PayrollRunView,
    PeriodClosingView,
    PITMonthlyReportView,
    PnLView,
    ProductCreateView,
    ProductDeleteView,
    ProductDetailView,
    ProductExportView,
    ProductListView,
    ProductUpdateView,
    ProjectAddPhaseView,
    ProjectAddResourceView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectListView,
    ProjectTogglePhaseView,
    PurchaseInvoiceCreateView,
    PurchaseInvoiceListView,
    RecurringListView,
    RecurringRunView,
    SalaryFundReportView,
    SalesInvoiceCreateView,
    SalesInvoiceListView,
    StockAdjustmentCreateView,
    StockAdjustmentListView,
    StockCardView,
    StockDashboardView,
    StockVoucherCreateView,
    StockVoucherListView,
    TicketCreateView,
    TicketListView,
    TrialBalanceDocxView,
    TrialBalanceView,
    VATReturnView,
    VendorCreateView,
    VendorDeleteView,
    VendorExportView,
    VendorListView,
    VendorUpdateView,
    VoucherCreateView,
    VoucherDeleteView,
    VoucherDetailView,
    VoucherExportView,
    VoucherListView,
    VoucherPrintDocxView,
    VoucherPrintView,
    VoucherUploadView,
)

app_name = "ui_modern"

urlpatterns = [
    path("", login_required(DashboardView.as_view()), name="dashboard"),
    path(
        "quick-expense/",
        login_required(QuickExpenseView.as_view()),
        name="dashboard_quick_expense",
    ),
    # Universal attachments
    path(
        "attachments/upload/",
        login_required(AttachmentUploadView.as_view()),
        name="attachment_upload",
    ),
    path(
        "attachments/<int:pk>/delete/",
        login_required(AttachmentDeleteView.as_view()),
        name="attachment_delete",
    ),
    path(
        "attachments/<int:pk>/download/",
        login_required(AttachmentDownloadView.as_view()),
        name="attachment_download",
    ),
    # Admin: roles + permissions + user assignment
    path(
        "me/permissions/",
        login_required(MyPermissionsView.as_view()),
        name="my_permissions",
    ),
    path(
        "admin/roles/",
        login_required(AdminRoleListView.as_view()),
        name="admin_role_list",
    ),
    path(
        "admin/roles/<int:pk>/edit/",
        login_required(AdminRoleEditView.as_view()),
        name="admin_role_edit",
    ),
    path(
        "admin/users/",
        login_required(AdminUserListView.as_view()),
        name="admin_user_list",
    ),
    path(
        "admin/users/<int:user_id>/assign/",
        login_required(AdminUserAssignView.as_view()),
        name="admin_user_assign",
    ),
    # Company profile
    path(
        "admin/company-profile/",
        login_required(CompanyProfileView.as_view()),
        name="company_profile",
    ),
    # Contact requests (from landing/blog)
    path(
        "admin/contacts/",
        login_required(ContactListAdminView.as_view()),
        name="admin_contact_list",
    ),
    # Approvals workflow
    path(
        "approvals/",
        login_required(ApprovalQueueView.as_view()),
        name="approval_queue",
    ),
    path(
        "approvals/rules/",
        login_required(ApprovalRuleListView.as_view()),
        name="approval_rules",
    ),
    path(
        "approvals/<int:pk>/",
        login_required(ApprovalDetailView.as_view()),
        name="approval_detail",
    ),
    path(
        "approvals/<int:pk>/approve/",
        login_required(ApprovalApproveView.as_view()),
        name="approval_approve",
    ),
    path(
        "approvals/<int:pk>/reject/",
        login_required(ApprovalRejectView.as_view()),
        name="approval_reject",
    ),
    # E-invoice (Hóa đơn điện tử)
    path(
        "einvoices/",
        login_required(EInvoiceListView.as_view()),
        name="einvoice_list",
    ),
    path(
        "einvoices/<int:pk>/",
        login_required(EInvoiceDetailView.as_view()),
        name="einvoice_detail",
    ),
    path(
        "einvoices/issue-from-sales/<int:sales_invoice_id>/",
        login_required(EInvoiceIssueFromSalesView.as_view()),
        name="einvoice_issue_from_sales",
    ),
    path(
        "einvoices/<int:pk>/publish/",
        login_required(EInvoicePublishView.as_view()),
        name="einvoice_publish",
    ),
    path(
        "einvoices/<int:pk>/cancel/",
        login_required(EInvoiceCancelView.as_view()),
        name="einvoice_cancel",
    ),
    path(
        "einvoices/<int:pk>/download/xml/",
        login_required(EInvoiceXmlDownloadView.as_view()),
        name="einvoice_download_xml",
    ),
    path(
        "einvoices/<int:pk>/download/json/",
        login_required(EInvoiceJsonDownloadView.as_view()),
        name="einvoice_download_json",
    ),
    path(
        "einvoices/reports/generate/",
        login_required(EInvoiceReportView.as_view()),
        name="einvoice_report_generate",
    ),
    # Banking (reconciliation) — declared directly for ui_modern:banking_* names
    path(
        "banking/accounts/",
        login_required(BankAccountListView.as_view()),
        name="banking_account_list",
    ),
    path(
        "banking/imports/",
        login_required(BankStatementImportListView.as_view()),
        name="banking_import_list",
    ),
    path(
        "banking/imports/upload/",
        login_required(BankStatementUploadView.as_view()),
        name="banking_import_upload",
    ),
    path(
        "banking/imports/<int:pk>/",
        login_required(BankStatementImportDetailView.as_view()),
        name="banking_import_detail",
    ),
    path(
        "banking/reconcile/",
        login_required(BankReconciliationView.as_view()),
        name="banking_reconcile",
    ),
    path(
        "banking/reconcile/run/",
        login_required(BankReconciliationRunView.as_view()),
        name="banking_reconcile_run",
    ),
    # Guarantees
    path(
        "guarantees/",
        login_required(BankGuaranteeListView.as_view()),
        name="guarantee_list",
    ),
    # Loans
    path(
        "loans/",
        login_required(BankLoanListView.as_view()),
        name="loan_list",
    ),
    # Bidding (P2.1)
    path(
        "bidding/",
        login_required(BidOpportunityListView.as_view()),
        name="bid_list",
    ),
    path(
        "bidding/<int:pk>/",
        login_required(BidOpportunityDetailView.as_view()),
        name="bid_detail",
    ),
    path(
        "bidding/<int:pk>/convert-to-contract/",
        login_required(BidConvertToContractView.as_view()),
        name="bid_convert_to_contract",
    ),
    # Budget + Cash flow (P2.2)
    path(
        "budget/",
        login_required(BudgetListView.as_view()),
        name="budget_list",
    ),
    path(
        "budget/<int:pk>/",
        login_required(BudgetDetailView.as_view()),
        name="budget_detail",
    ),
    path(
        "budget/generate/",
        login_required(BudgetGenerateView.as_view()),
        name="budget_generate",
    ),
    path(
        "budget/<int:pk>/refresh/",
        login_required(BudgetRefreshActualsView.as_view()),
        name="budget_refresh",
    ),
    path(
        "cash-flow/",
        login_required(CashFlowView.as_view()),
        name="cash_flow",
    ),
    path(
        "cash-flow/generate/",
        login_required(CashFlowGenerateView.as_view()),
        name="cash_flow_generate",
    ),
    # FX (P2.3)
    path(
        "fx/rates/",
        login_required(ExchangeRateListView.as_view()),
        name="fx_rate_list",
    ),
    path(
        "fx/revaluation/",
        login_required(FxRevaluationListView.as_view()),
        name="fx_revaluation_list",
    ),
    path(
        "fx/revaluation/run/",
        login_required(FxRevaluationRunView.as_view()),
        name="fx_revaluation_run",
    ),
    path(
        "vouchers/",
        login_required(VoucherListView.as_view()),
        name="voucher_list",
    ),
    path(
        "vouchers/new/",
        login_required(VoucherCreateView.as_view()),
        name="voucher_create",
    ),
    path(
        "vouchers/<int:pk>/",
        login_required(VoucherDetailView.as_view()),
        name="voucher_detail",
    ),
    path(
        "vouchers/<int:pk>/print/",
        login_required(VoucherPrintView.as_view()),
        name="voucher_print",
    ),
    path(
        "vouchers/<int:pk>/print-docx/",
        login_required(VoucherPrintDocxView.as_view()),
        name="voucher_print_docx",
    ),
    path(
        "vouchers/<int:pk>/upload/",
        login_required(VoucherUploadView.as_view()),
        name="voucher_upload",
    ),
    path(
        "vouchers/export/",
        login_required(VoucherExportView.as_view()),
        name="voucher_export",
    ),
    path(
        "vouchers/<int:pk>/delete/",
        login_required(VoucherDeleteView.as_view()),
        name="voucher_delete",
    ),
    path(
        "documents/<int:pk>/download/",
        login_required(DocumentDownloadView.as_view()),
        name="document_download",
    ),
    path(
        "documents/<int:pk>/delete/",
        login_required(DocumentDeleteView.as_view()),
        name="document_delete",
    ),
    path(
        "reports/trial-balance/",
        login_required(TrialBalanceView.as_view()),
        name="trial_balance",
    ),
    path(
        "reports/trial-balance/docx/",
        login_required(TrialBalanceDocxView.as_view()),
        name="trial_balance_docx",
    ),
    path(
        "contracts/<int:pk>/export-docx/",
        login_required(ContractExportDocxView.as_view()),
        name="contract_export_docx",
    ),
    path(
        "reports/balance-sheet/",
        login_required(BalanceSheetView.as_view()),
        name="balance_sheet",
    ),
    path(
        "reports/pnl/",
        login_required(PnLView.as_view()),
        name="pnl",
    ),
    path(
        "reports/vat-return/",
        login_required(VATReturnView.as_view()),
        name="vat_return",
    ),
    path(
        "reports/general-journal/",
        login_required(GeneralJournalView.as_view()),
        name="general_journal",
    ),
    path(
        "reports/general-ledger/",
        login_required(GeneralLedgerView.as_view()),
        name="general_ledger",
    ),
    path(
        "reports/d62/",
        login_required(D62ReportView.as_view()),
        name="report_d62",
    ),
    path(
        "reports/labor-usage/",
        login_required(LaborUsageReportView.as_view()),
        name="report_labor_usage",
    ),
    path(
        "reports/salary-fund/",
        login_required(SalaryFundReportView.as_view()),
        name="report_salary_fund",
    ),
    path(
        "reports/pit-monthly/",
        login_required(PITMonthlyReportView.as_view()),
        name="report_pit_monthly",
    ),
    # Master data — Customer
    path(
        "customers/",
        login_required(CustomerListView.as_view()),
        name="customer_list",
    ),
    path(
        "customers/new/",
        login_required(CustomerCreateView.as_view()),
        name="customer_create",
    ),
    path(
        "customers/<int:pk>/edit/",
        login_required(CustomerUpdateView.as_view()),
        name="customer_update",
    ),
    path(
        "customers/export/",
        login_required(CustomerExportView.as_view()),
        name="customer_export",
    ),
    path(
        "customers/<int:pk>/delete/",
        login_required(CustomerDeleteView.as_view()),
        name="customer_delete",
    ),
    # Master data — Vendor
    path(
        "vendors/",
        login_required(VendorListView.as_view()),
        name="vendor_list",
    ),
    path(
        "vendors/new/",
        login_required(VendorCreateView.as_view()),
        name="vendor_create",
    ),
    path(
        "vendors/<int:pk>/edit/",
        login_required(VendorUpdateView.as_view()),
        name="vendor_update",
    ),
    path(
        "vendors/export/",
        login_required(VendorExportView.as_view()),
        name="vendor_export",
    ),
    path(
        "vendors/<int:pk>/delete/",
        login_required(VendorDeleteView.as_view()),
        name="vendor_delete",
    ),
    # Master data — Product
    path(
        "products/",
        login_required(ProductListView.as_view()),
        name="product_list",
    ),
    path(
        "products/new/",
        login_required(ProductCreateView.as_view()),
        name="product_create",
    ),
    path(
        "products/<int:pk>/edit/",
        login_required(ProductUpdateView.as_view()),
        name="product_update",
    ),
    path(
        "products/<int:pk>/",
        login_required(ProductDetailView.as_view()),
        name="product_detail",
    ),
    path(
        "products/export/",
        login_required(ProductExportView.as_view()),
        name="product_export",
    ),
    path(
        "products/<int:pk>/delete/",
        login_required(ProductDeleteView.as_view()),
        name="product_delete",
    ),
    # Sales invoices
    path(
        "sales-invoices/",
        login_required(SalesInvoiceListView.as_view()),
        name="sales_invoice_list",
    ),
    path(
        "sales-invoices/new/",
        login_required(SalesInvoiceCreateView.as_view()),
        name="sales_invoice_create",
    ),
    # Purchase invoices
    path(
        "purchase-invoices/",
        login_required(PurchaseInvoiceListView.as_view()),
        name="purchase_invoice_list",
    ),
    path(
        "purchase-invoices/new/",
        login_required(PurchaseInvoiceCreateView.as_view()),
        name="purchase_invoice_create",
    ),
    # Stock vouchers
    path(
        "stock-vouchers/",
        login_required(StockVoucherListView.as_view()),
        name="stock_voucher_list",
    ),
    path(
        "stock-vouchers/new/",
        login_required(StockVoucherCreateView.as_view()),
        name="stock_voucher_create",
    ),
    # Stock dashboard + adjustments + stock card
    path(
        "inventory/dashboard/",
        login_required(StockDashboardView.as_view()),
        name="stock_dashboard",
    ),
    path(
        "inventory/adjustments/",
        login_required(StockAdjustmentListView.as_view()),
        name="stock_adjustment_list",
    ),
    path(
        "inventory/adjustments/new/",
        login_required(StockAdjustmentCreateView.as_view()),
        name="stock_adjustment_create",
    ),
    path(
        "inventory/stock-card/",
        login_required(StockCardView.as_view()),
        name="stock_card_report",
    ),
    # Fixed assets
    path(
        "assets/",
        login_required(AssetListView.as_view()),
        name="asset_list",
    ),
    path(
        "assets/new/",
        login_required(AssetCreateView.as_view()),
        name="asset_create",
    ),
    path(
        "assets/depreciation/",
        login_required(DepreciationRunView.as_view()),
        name="depreciation_run",
    ),
    path(
        "assets/<int:pk>/dispose/",
        login_required(AssetDisposeView.as_view()),
        name="asset_dispose",
    ),
    path(
        "assets/<int:pk>/transfer/",
        login_required(AssetTransferView.as_view()),
        name="asset_transfer",
    ),
    path(
        "assets/transactions/",
        login_required(AssetTransactionListView.as_view()),
        name="asset_transaction_list",
    ),
    # HR — employees
    path(
        "employees/",
        login_required(EmployeeListView.as_view()),
        name="employee_list",
    ),
    path(
        "employees/new/",
        login_required(EmployeeCreateView.as_view()),
        name="employee_create",
    ),
    # HR — Labor contracts
    path(
        "labor-contracts/",
        login_required(LaborContractListView.as_view()),
        name="labor_contract_list",
    ),
    # Chart of accounts (TT133)
    path(
        "chart-of-accounts/",
        login_required(ChartOfAccountsListView.as_view()),
        name="chart_of_accounts_list",
    ),
    path(
        "labor-contracts/new/",
        login_required(LaborContractCreateView.as_view()),
        name="labor_contract_create",
    ),
    # HR — Dependents
    path(
        "dependents/",
        login_required(DependentListView.as_view()),
        name="dependent_list",
    ),
    # HR — Leave request
    path(
        "leave/request/",
        login_required(LeaveRequestView.as_view()),
        name="leave_request",
    ),
    # HR — Insurance dashboard
    path(
        "insurance/",
        login_required(InsuranceDashboardView.as_view()),
        name="insurance_dashboard",
    ),
    # Payroll
    path(
        "payroll/run/",
        login_required(PayrollRunView.as_view()),
        name="payroll_run",
    ),
    # Period closing
    path(
        "closing/",
        login_required(PeriodClosingView.as_view()),
        name="period_closing",
    ),
    # Treasury — phiếu thu / phiếu chi
    path(
        "treasury/receipt/new/",
        login_required(CashReceiptCreateView.as_view()),
        name="cash_receipt_create",
    ),
    path(
        "treasury/payment/new/",
        login_required(CashPaymentCreateView.as_view()),
        name="cash_payment_create",
    ),
    # Contracts
    path(
        "contracts/",
        login_required(ContractListView.as_view()),
        name="contract_list",
    ),
    path(
        "contracts/new/",
        login_required(ContractCreateView.as_view()),
        name="contract_create",
    ),
    path(
        "contracts/<int:pk>/",
        login_required(ContractDetailView.as_view()),
        name="contract_detail",
    ),
    # Contract templates — full CRUD
    path(
        "contract-templates/",
        login_required(ContractTemplateListView.as_view()),
        name="contract_template_list",
    ),
    path(
        "contract-templates/new/",
        login_required(ContractTemplateCreateView.as_view()),
        name="contract_template_create",
    ),
    path(
        "contract-templates/duplicate/<int:pk>/",
        login_required(ContractTemplateCreateView.as_view()),
        name="contract_template_duplicate",
    ),
    path(
        "contract-templates/<int:pk>/edit/",
        login_required(ContractTemplateEditView.as_view()),
        name="contract_template_edit",
    ),
    path(
        "contract-templates/<int:pk>/delete/",
        login_required(ContractTemplateDeleteView.as_view()),
        name="contract_template_delete",
    ),
    path(
        "contract-templates/preview-raw/",
        login_required(ContractTemplatePreviewRawView.as_view()),
        name="contract_template_preview_raw",
    ),
    path(
        "contract-templates/generate/<str:template_code>/<int:contract_id>/",
        login_required(ContractGenerateView.as_view()),
        name="contract_template_generate",
    ),
    # Input invoices (đầu vào)
    path(
        "input-invoices/",
        login_required(InputInvoiceListView.as_view()),
        name="input_invoice_list",
    ),
    path(
        "input-invoices/upload/",
        login_required(InputInvoiceUploadView.as_view()),
        name="input_invoice_upload",
    ),
    path(
        "input-invoices/<int:pk>/process/",
        login_required(InputInvoiceProcessView.as_view()),
        name="input_invoice_process",
    ),
    # Recurring entries
    path(
        "recurring/",
        login_required(RecurringListView.as_view()),
        name="recurring_list",
    ),
    path(
        "recurring/run/",
        login_required(RecurringRunView.as_view()),
        name="recurring_run",
    ),
    # Project Management
    path(
        "projects/",
        login_required(ProjectListView.as_view()),
        name="project_list",
    ),
    path(
        "projects/new/",
        login_required(ProjectCreateView.as_view()),
        name="project_create",
    ),
    path(
        "projects/<int:pk>/",
        login_required(ProjectDetailView.as_view()),
        name="project_detail",
    ),
    path(
        "projects/<int:pk>/phases/add/",
        login_required(ProjectAddPhaseView.as_view()),
        name="project_phase_add",
    ),
    path(
        "projects/<int:pk>/phases/<int:phase_pk>/toggle/",
        login_required(ProjectTogglePhaseView.as_view()),
        name="project_phase_toggle",
    ),
    path(
        "projects/<int:pk>/resources/add/",
        login_required(ProjectAddResourceView.as_view()),
        name="project_resource_add",
    ),
    # CRM
    path(
        "crm/leads/",
        login_required(LeadListView.as_view()),
        name="crm_lead_list",
    ),
    path(
        "crm/leads/new/",
        login_required(LeadCreateView.as_view()),
        name="crm_lead_create",
    ),
    path(
        "crm/accounts/new/",
        login_required(AccountCreateView.as_view()),
        name="crm_account_create",
    ),
    path(
        "crm/opportunities/",
        login_required(OpportunityListView.as_view()),
        name="crm_opportunity_list",
    ),
    path(
        "crm/opportunities/new/",
        login_required(OpportunityCreateView.as_view()),
        name="crm_opportunity_create",
    ),
    path(
        "crm/opportunities/<int:pk>/",
        login_required(OpportunityDetailView.as_view()),
        name="crm_opportunity_detail",
    ),
    path(
        "crm/opportunities/<int:pk>/convert/",
        login_required(OpportunityConvertView.as_view()),
        name="crm_opportunity_convert",
    ),
    path(
        "crm/tickets/",
        login_required(TicketListView.as_view()),
        name="crm_ticket_list",
    ),
    path(
        "crm/tickets/new/",
        login_required(TicketCreateView.as_view()),
        name="crm_ticket_create",
    ),
    path(
        "crm/campaigns/",
        login_required(CampaignListView.as_view()),
        name="crm_campaign_list",
    ),
    path(
        "crm/campaigns/new/",
        login_required(CampaignCreateView.as_view()),
        name="crm_campaign_create",
    ),
]
