from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (
    AssetCreateView,
    AssetListView,
    BalanceSheetView,
    CashPaymentCreateView,
    CashReceiptCreateView,
    ContractCreateView,
    ContractListView,
    CustomerCreateView,
    CustomerListView,
    CustomerUpdateView,
    D62ReportView,
    DashboardView,
    DependentListView,
    DepreciationRunView,
    DocumentDeleteView,
    DocumentDownloadView,
    EmployeeCreateView,
    EmployeeListView,
    GeneralJournalView,
    GeneralLedgerView,
    InputInvoiceListView,
    InputInvoiceProcessView,
    InputInvoiceUploadView,
    InsuranceDashboardView,
    LaborContractCreateView,
    LaborContractListView,
    LaborUsageReportView,
    LeaveRequestView,
    PayrollRunView,
    PeriodClosingView,
    PITMonthlyReportView,
    PnLView,
    ProductCreateView,
    ProductListView,
    ProductUpdateView,
    PurchaseInvoiceCreateView,
    PurchaseInvoiceListView,
    RecurringListView,
    RecurringRunView,
    SalaryFundReportView,
    SalesInvoiceCreateView,
    SalesInvoiceListView,
    StockVoucherCreateView,
    StockVoucherListView,
    TrialBalanceView,
    VATReturnView,
    VendorCreateView,
    VendorListView,
    VendorUpdateView,
    VoucherCreateView,
    VoucherDetailView,
    VoucherListView,
    VoucherPrintView,
    VoucherUploadView,
)

app_name = "ui_modern"

urlpatterns = [
    path("", login_required(DashboardView.as_view()), name="dashboard"),
    path(
        "vouchers/",
        login_required(VoucherListView.as_view()),
        name="voucher_list",
    ),
    path(
        "vouchers/new/",
        login_required(VoucherCreateView.as_view()),
        name="voucher_create",
    ),
    path(
        "vouchers/<int:pk>/",
        login_required(VoucherDetailView.as_view()),
        name="voucher_detail",
    ),
    path(
        "vouchers/<int:pk>/print/",
        login_required(VoucherPrintView.as_view()),
        name="voucher_print",
    ),
    path(
        "vouchers/<int:pk>/upload/",
        login_required(VoucherUploadView.as_view()),
        name="voucher_upload",
    ),
    path(
        "documents/<int:pk>/download/",
        login_required(DocumentDownloadView.as_view()),
        name="document_download",
    ),
    path(
        "documents/<int:pk>/delete/",
        login_required(DocumentDeleteView.as_view()),
        name="document_delete",
    ),
    path(
        "reports/trial-balance/",
        login_required(TrialBalanceView.as_view()),
        name="trial_balance",
    ),
    path(
        "reports/balance-sheet/",
        login_required(BalanceSheetView.as_view()),
        name="balance_sheet",
    ),
    path(
        "reports/pnl/",
        login_required(PnLView.as_view()),
        name="pnl",
    ),
    path(
        "reports/vat-return/",
        login_required(VATReturnView.as_view()),
        name="vat_return",
    ),
    path(
        "reports/general-journal/",
        login_required(GeneralJournalView.as_view()),
        name="general_journal",
    ),
    path(
        "reports/general-ledger/",
        login_required(GeneralLedgerView.as_view()),
        name="general_ledger",
    ),
    path(
        "reports/d62/",
        login_required(D62ReportView.as_view()),
        name="report_d62",
    ),
    path(
        "reports/labor-usage/",
        login_required(LaborUsageReportView.as_view()),
        name="report_labor_usage",
    ),
    path(
        "reports/salary-fund/",
        login_required(SalaryFundReportView.as_view()),
        name="report_salary_fund",
    ),
    path(
        "reports/pit-monthly/",
        login_required(PITMonthlyReportView.as_view()),
        name="report_pit_monthly",
    ),
    # Master data — Customer
    path(
        "customers/",
        login_required(CustomerListView.as_view()),
        name="customer_list",
    ),
    path(
        "customers/new/",
        login_required(CustomerCreateView.as_view()),
        name="customer_create",
    ),
    path(
        "customers/<int:pk>/edit/",
        login_required(CustomerUpdateView.as_view()),
        name="customer_update",
    ),
    # Master data — Vendor
    path(
        "vendors/",
        login_required(VendorListView.as_view()),
        name="vendor_list",
    ),
    path(
        "vendors/new/",
        login_required(VendorCreateView.as_view()),
        name="vendor_create",
    ),
    path(
        "vendors/<int:pk>/edit/",
        login_required(VendorUpdateView.as_view()),
        name="vendor_update",
    ),
    # Master data — Product
    path(
        "products/",
        login_required(ProductListView.as_view()),
        name="product_list",
    ),
    path(
        "products/new/",
        login_required(ProductCreateView.as_view()),
        name="product_create",
    ),
    path(
        "products/<int:pk>/edit/",
        login_required(ProductUpdateView.as_view()),
        name="product_update",
    ),
    # Sales invoices
    path(
        "sales-invoices/",
        login_required(SalesInvoiceListView.as_view()),
        name="sales_invoice_list",
    ),
    path(
        "sales-invoices/new/",
        login_required(SalesInvoiceCreateView.as_view()),
        name="sales_invoice_create",
    ),
    # Purchase invoices
    path(
        "purchase-invoices/",
        login_required(PurchaseInvoiceListView.as_view()),
        name="purchase_invoice_list",
    ),
    path(
        "purchase-invoices/new/",
        login_required(PurchaseInvoiceCreateView.as_view()),
        name="purchase_invoice_create",
    ),
    # Stock vouchers
    path(
        "stock-vouchers/",
        login_required(StockVoucherListView.as_view()),
        name="stock_voucher_list",
    ),
    path(
        "stock-vouchers/new/",
        login_required(StockVoucherCreateView.as_view()),
        name="stock_voucher_create",
    ),
    # Fixed assets
    path(
        "assets/",
        login_required(AssetListView.as_view()),
        name="asset_list",
    ),
    path(
        "assets/new/",
        login_required(AssetCreateView.as_view()),
        name="asset_create",
    ),
    path(
        "assets/depreciation/",
        login_required(DepreciationRunView.as_view()),
        name="depreciation_run",
    ),
    # HR — employees
    path(
        "employees/",
        login_required(EmployeeListView.as_view()),
        name="employee_list",
    ),
    path(
        "employees/new/",
        login_required(EmployeeCreateView.as_view()),
        name="employee_create",
    ),
    # HR — Labor contracts
    path(
        "labor-contracts/",
        login_required(LaborContractListView.as_view()),
        name="labor_contract_list",
    ),
    path(
        "labor-contracts/new/",
        login_required(LaborContractCreateView.as_view()),
        name="labor_contract_create",
    ),
    # HR — Dependents
    path(
        "dependents/",
        login_required(DependentListView.as_view()),
        name="dependent_list",
    ),
    # HR — Leave request
    path(
        "leave/request/",
        login_required(LeaveRequestView.as_view()),
        name="leave_request",
    ),
    # HR — Insurance dashboard
    path(
        "insurance/",
        login_required(InsuranceDashboardView.as_view()),
        name="insurance_dashboard",
    ),
    # Payroll
    path(
        "payroll/run/",
        login_required(PayrollRunView.as_view()),
        name="payroll_run",
    ),
    # Period closing
    path(
        "closing/",
        login_required(PeriodClosingView.as_view()),
        name="period_closing",
    ),
    # Treasury — phiếu thu / phiếu chi
    path(
        "treasury/receipt/new/",
        login_required(CashReceiptCreateView.as_view()),
        name="cash_receipt_create",
    ),
    path(
        "treasury/payment/new/",
        login_required(CashPaymentCreateView.as_view()),
        name="cash_payment_create",
    ),
    # Contracts
    path(
        "contracts/",
        login_required(ContractListView.as_view()),
        name="contract_list",
    ),
    path(
        "contracts/new/",
        login_required(ContractCreateView.as_view()),
        name="contract_create",
    ),
    # Input invoices (đầu vào)
    path(
        "input-invoices/",
        login_required(InputInvoiceListView.as_view()),
        name="input_invoice_list",
    ),
    path(
        "input-invoices/upload/",
        login_required(InputInvoiceUploadView.as_view()),
        name="input_invoice_upload",
    ),
    path(
        "input-invoices/<int:pk>/process/",
        login_required(InputInvoiceProcessView.as_view()),
        name="input_invoice_process",
    ),
    # Recurring entries
    path(
        "recurring/",
        login_required(RecurringListView.as_view()),
        name="recurring_list",
    ),
    path(
        "recurring/run/",
        login_required(RecurringRunView.as_view()),
        name="recurring_run",
    ),
]
