# Generated by Django 5.2.15 on 2026-07-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('B01-DN', 'Bảng cân đối kế toán (B01-DN)'), ('B02-DN', 'Báo cáo kết quả HĐKD (B02-DN)'), ('B03-DN-direct', 'BC dòng tiền PP trực tiếp (B03-DN)'), ('B03-DN-indirect', 'BC dòng tiền PP gián tiếp (B03-DN)')], db_index=True, max_length=30)),
                ('stt', models.CharField(blank=True, default='', max_length=20)),
                ('ma_so', models.CharField(blank=True, default='', max_length=20)),
                ('chi_tieu', models.CharField(max_length=300)),
                ('thuyet_minh', models.CharField(blank=True, default='', max_length=500)),
                ('tk_no_pattern', models.CharField(blank=True, default='', max_length=100)),
                ('tk_co_pattern', models.CharField(blank=True, default='', max_length=100)),
                ('cong_thuc', models.CharField(blank=True, default='', max_length=500)),
                ('tinh_giam_tru', models.CharField(blank=True, default='', max_length=500)),
                ('is_header', models.BooleanField(default=False)),
                ('parent_ma_so', models.CharField(blank=True, default='', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reporting_financial_report_line',
                'ordering': ['report_type', 'display_order'],
                'indexes': [models.Index(fields=['report_type', 'display_order'], name='reporting_f_report__5b35b0_idx')],
                'unique_together': {('report_type', 'display_order')},
            },
        ),
    ]
