# Generated by Django 5.2.15 on 2026-07-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_financialreportline_tk_doi_ung_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(help_text="Mã dòng trên tờ khai, e.g. '21', '22', '40'.", max_length=20, unique=True)),
                ('section', models.CharField(choices=[('A', 'A — Thông tin chung'), ('B-I', 'B.I — Hàng hóa dịch vụ mua vào'), ('B-II', 'B.II — Hàng hóa dịch vụ bán ra'), ('C', 'C — Thuế GTGT của hoạt động SXKD')], default='A', max_length=10)),
                ('stt', models.CharField(blank=True, default='', max_length=20)),
                ('chi_tieu', models.CharField(max_length=300)),
                ('thuyet_minh', models.CharField(blank=True, default='', max_length=500)),
                ('tk_filter', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_group_filter', models.CharField(blank=True, default='', max_length=10)),
                ('tax_code_filter', models.CharField(blank=True, default='', max_length=10)),
                ('amount_field', models.CharField(choices=[('tax_amount_vnd', 'Tiền thuế GTGT'), ('goods_amount_vnd', 'Tiền hàng hóa/dịch vụ'), ('debit_vnd', 'PS Nợ'), ('credit_vnd', 'PS Có')], default='tax_amount_vnd', max_length=30)),
                ('cong_thuc', models.CharField(blank=True, default='', max_length=500)),
                ('is_header', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reporting_vat_report_line',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['display_order'], name='reporting_v_display_ae1a81_idx')],
            },
        ),
    ]
