---
title: Visota Monitor
theme: dark
color: indigo
headerStyle: boxed
language: vi
hideVersion: true
iconStyle: theme
layout:
  Giám sát hệ thống:
    style: row
    columns: 3
  Visota:
    style: row
    columns: 3
  Hạ tầng:
    style: row
    columns: 2
quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true
    hideVisitURL: true
showStats: true
target: _blank
