# Generated by Django 5.2.15 on 2026-07-08 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_featureflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkm_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pkm_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='', help_text='Markdown content')),
                ('role_context', models.CharField(blank=True, default='', help_text="Optional role tag for context filtering (e.g. 'accountant')", max_length=100)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkm_notes', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='pkm.tag')),
            ],
            options={
                'db_table': 'pkm_knowledge_note',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini'), ('groq', 'Groq'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama')], max_length=20)),
                ('api_key_encrypted', models.TextField(blank=True, default='', help_text='Fernet-encrypted API key (never store plaintext)')),
                ('api_base', models.URLField(blank=True, default='', help_text='Custom API base URL for self-hosted or compatible endpoints')),
                ('default_model', models.CharField(max_length=100)),
                ('default_embedding_model', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkm_llm_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pkm_user_llm_config',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'company'], name='pkm_tag_user_id_e7d4c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'company', 'name'), name='unique_tag_user_company_name'),
        ),
        migrations.AddIndex(
            model_name='knowledgenote',
            index=models.Index(fields=['user', 'company'], name='pkm_knowled_user_id_2b62f2_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgenote',
            index=models.Index(fields=['user', 'company', 'is_pinned'], name='pkm_knowled_user_id_ea85f6_idx'),
        ),
        migrations.AddIndex(
            model_name='userllmconfig',
            index=models.Index(fields=['user', 'company'], name='pkm_user_ll_user_id_95767b_idx'),
        ),
        migrations.AddIndex(
            model_name='userllmconfig',
            index=models.Index(fields=['user', 'company', 'is_active'], name='pkm_user_ll_user_id_d9f91d_idx'),
        ),
        migrations.AddConstraint(
            model_name='userllmconfig',
            constraint=models.UniqueConstraint(fields=('user', 'company', 'provider'), name='unique_llm_config_user_company_provider'),
        ),
    ]
