# Generated by Django 5.2.15 on 2026-07-08 21:16

import apps.pkm.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_featureflag'),
        ('pkm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PKMDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(help_text='Uploaded document file for RAG processing', upload_to='pkm/docs/%Y/%m/')),
                ('file_type', models.CharField(help_text='File extension/type (e.g. pdf, docx, txt, md)', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA-256 checksum for deduplication', max_length=64)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if processing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkm_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pkm_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(help_text='Zero-based ordinal position within the document')),
                ('content', models.TextField(help_text='The extracted text content for this chunk')),
                ('token_count', models.IntegerField(default=0, help_text='Number of tokens in this chunk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='pkm.pkmdocument')),
            ],
            options={
                'db_table': 'pkm_documentchunk',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', help_text='Cached text content that was embedded')),
                ('model_name', models.CharField(help_text='Name of the embedding model used (e.g. text-embedding-3-small)', max_length=100)),
                ('embedding', apps.pkm.fields.VectorField(default=None, dimensions=1536, editable=False, help_text='1536-dim vector (stored via VEC_FromText raw SQL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='pkm.documentchunk')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkm_embeddings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pkm_embedding',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'company'], name='pkm_embeddi_user_id_921b91_idx'), models.Index(fields=['chunk'], name='pkm_embeddi_chunk_i_18137c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pkmdocument',
            index=models.Index(fields=['user', 'company'], name='pkm_documen_user_id_4d3317_idx'),
        ),
        migrations.AddIndex(
            model_name='pkmdocument',
            index=models.Index(fields=['user', 'company', 'status'], name='pkm_documen_user_id_7d8283_idx'),
        ),
        migrations.AddIndex(
            model_name='pkmdocument',
            index=models.Index(fields=['checksum'], name='pkm_documen_checksu_048d79_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document'], name='pkm_documen_documen_766b19_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='pkm_documen_documen_ac0d0a_idx'),
        ),
        # HNSW vector index for fast cosine similarity search (raw SQL because
        # Django ORM cannot express MariaDB VECTOR INDEX syntax).
        migrations.RunSQL(
            sql=(
                "CREATE VECTOR INDEX pkm_embedding_vec_idx "
                "ON pkm_embedding (embedding) "
                "M=8 DISTANCE=cosine;"
            ),
            reverse_sql="DROP VECTOR INDEX pkm_embedding_vec_idx ON pkm_embedding;",
        ),
    ]
