# Generated by Django 5.2.15 on 2026-07-08 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_featureflag'),
        ('pkm', '0002_document_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text="The user's question")),
                ('answer', models.TextField(blank=True, default='', help_text='The generated answer')),
                ('sources', models.JSONField(blank=True, default=list, help_text='List of source references (chunk_id, document_title, preview)')),
                ('context_used', models.JSONField(blank=True, default=list, help_text='List of context chunks/notes used to build the prompt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkm_qa_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pkm_qa_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'company'], name='pkm_qa_hist_user_id_ae15c3_idx'), models.Index(fields=['user', 'company', '-created_at'], name='pkm_qa_hist_user_id_f6ea6f_idx')],
            },
        ),
    ]
