# Generated by Django 5.2.15 on 2026-07-09 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_featureflag'),
        ('pkm', '0003_qa_history_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('page_view', 'Page View'), ('search', 'Search'), ('note_create', 'Note Create'), ('document_create', 'Document Create'), ('voucher_create', 'Voucher Create')], max_length=20)),
                ('module', models.CharField(help_text="Which Visota module the interaction occurred in (e.g. 'ledger', 'pkm')", max_length=50)),
                ('entity_type', models.CharField(blank=True, default='', help_text="Optional entity type (e.g. 'note', 'document', 'voucher')", max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', help_text='Optional entity identifier as a string', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form JSON metadata (search query, page URL, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkm_interaction_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pkm_user_interaction_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'company'], name='pkm_user_in_user_id_93b476_idx'), models.Index(fields=['user', 'company', '-created_at'], name='pkm_user_in_user_id_582806_idx')],
            },
        ),
    ]
