# Generated by Django 5.2.15 on 2026-07-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkm', '0004_userinteractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='qahistory',
            name='interaction_context',
            field=models.TextField(blank=True, default='', help_text="Summary of the user's recent activity (from interaction_service)"),
        ),
    ]
