# Generated by Django 5.2.15 on 2026-07-16 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_company_industry_field"),
        ("pkm", "0007_pkmdocument_is_system"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WikiPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", help_text="Markdown content"
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("concept", "Concept"),
                            ("entity", "Entity"),
                            ("overview", "Overview"),
                            ("synthesis", "Synthesis"),
                        ],
                        default="summary",
                        help_text="Wiki page type (summary/concept/entity/overview/synthesis)",
                        max_length=20,
                    ),
                ),
                (
                    "is_ai_generated",
                    models.BooleanField(
                        default=False,
                        help_text="True if authored/synthesised by the LLM ingest pipeline",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="True for shared cross-tenant system pages (e.g. regulation overviews)",
                    ),
                ),
                (
                    "last_ingest_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the wiki ingest pipeline last updated this page",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pkm_wiki_page",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="pkmdocument",
            new_name="pkm_documen_is_syst_2371c0_idx",
            old_name="pkm_doc_is_system_idx",
        ),
        migrations.AddField(
            model_name="wikipage",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="linked_pages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Cross-references to other wiki pages ([[wikilinks]])",
                to="pkm.wikipage",
            ),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="source_refs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Source documents that informed this page",
                related_name="wiki_pages",
                to="pkm.pkmdocument",
            ),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="wiki_pages", to="pkm.tag"
            ),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pkm_wiki_pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="wikipage",
            index=models.Index(
                fields=["user", "company"], name="pkm_wiki_pa_user_id_a3fba4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wikipage",
            index=models.Index(
                fields=["user", "company", "page_type"],
                name="pkm_wiki_pa_user_id_c4acc6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wikipage",
            index=models.Index(
                fields=["is_system"], name="pkm_wiki_pa_is_syst_006d88_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wikipage",
            constraint=models.UniqueConstraint(
                fields=("user", "company", "title"),
                name="unique_wiki_page_user_company_title",
            ),
        ),
    ]
