# Generated by Django 5.2.15 on 2026-07-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pkm", "0008_wiki_page_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="userllmconfig",
            name="disable_masking",
            field=models.BooleanField(
                default=False,
                help_text="When True, PII data (MST, VND amounts, phone, email) is NOT masked before LLM calls. Useful for local Ollama models where data never leaves the machine. Default False = mask everything (secure).",
            ),
        ),
    ]
