# Generated by Django 5.2.15 on 2026-06-22 16:04

import apps.core.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_pit_history_and_bidding'),
        ('core', '0007_alter_taxrateconfig_pit_dependent_deduction_and_more'),
        ('ledger', '0002_accountperiodbalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantee_no', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('guarantee_type', models.CharField(choices=[('bid_bond', 'Bảo lãnh dự thầu'), ('performance', 'Bảo lãnh thực hợp đồng'), ('advance_payment', 'Bảo lãnh ứng trước'), ('warranty', 'Bảo lãnh bảo hành'), ('other', 'Khác')], default='performance', max_length=20)),
                ('bank_account', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('beneficiary_tax_code', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Dự thảo'), ('active', 'Hiệu lực'), ('released', 'Đã giải chấp'), ('expired', 'Quá hạn'), ('cancelled', 'Đã hủy')], default='draft', max_length=20)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('margin_deposit_account', models.CharField(default='244', max_length=20)),
                ('fee_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantees', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gl_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantees_issued', to='ledger.accountingvoucher')),
                ('release_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantees_released', to='ledger.accountingvoucher')),
            ],
            options={
                'db_table': 'bank_guarantee',
                'ordering': ['-issue_date', '-id'],
                'unique_together': {('company', 'guarantee_no')},
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
    ]
