# Generated by Django 5.2.15 on 2026-06-17 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('full_name', models.TextField()),
                ('issuing_body', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('applicable_to', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='core.legalreference')),
            ],
            options={
                'db_table': 'legal_reference',
                'ordering': ['code'],
            },
        ),
    ]
