# Generated by Django 5.2.15 on 2026-06-17 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_legalreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='annual_revenue',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='company',
            name='sme_size',
            field=models.CharField(choices=[('micro', 'Siêu nhỏ'), ('small', 'Nhỏ'), ('medium', 'Vừa'), ('large', 'Lớn')], default='small', max_length=10),
        ),
        migrations.CreateModel(
            name='TaxRateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cit_rate_standard', models.DecimalField(decimal_places=4, default=0.2, max_digits=6)),
                ('cit_rate_small', models.DecimalField(decimal_places=4, default=0.17, max_digits=6)),
                ('cit_rate_micro', models.DecimalField(decimal_places=4, default=0.15, max_digits=6)),
                ('vat_rate_standard', models.DecimalField(decimal_places=4, default=0.1, max_digits=6)),
                ('vat_rate_reduced', models.DecimalField(decimal_places=4, default=0.08, max_digits=6)),
                ('vat_rate_reduced_active', models.BooleanField(default=True)),
                ('pit_personal_deduction', models.DecimalField(decimal_places=4, default=11000000, max_digits=15)),
                ('pit_dependent_deduction', models.DecimalField(decimal_places=4, default=4400000, max_digits=15)),
                ('bhxh_cap', models.DecimalField(decimal_places=4, default=46800000, max_digits=15)),
                ('base_salary', models.DecimalField(decimal_places=4, default=2340000, max_digits=15)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'tax_rate_config',
                'ordering': ['-effective_date'],
            },
        ),
    ]
