# Generated by Django 5.2.15 on 2026-06-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_annual_revenue_company_sme_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrateconfig',
            name='pit_brackets',
            field=models.JSONField(default=list, help_text='[[5000000, 0.05], [10000000, 0.10], ...]'),
        ),
    ]
