# Generated by Django 5.2.15 on 2026-06-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_taxrateconfig_pit_brackets'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('current_rate_text', models.TextField(help_text='Human-readable rate description')),
                ('legal_basis', models.CharField(blank=True, default='', max_length=100)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tax_type',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='fct_cit_rate',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=6),
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='fct_vat_rate',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=6),
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='fee_monbai_over_10b',
            field=models.DecimalField(decimal_places=4, default=3000000, max_digits=15),
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='fee_monbai_under_10b',
            field=models.DecimalField(decimal_places=4, default=2000000, max_digits=15),
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='fee_truoc_ba_other',
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=6),
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='fee_truoc_ba_real_estate',
            field=models.DecimalField(decimal_places=4, default=0.005, max_digits=6),
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='pit_brackets_2026',
            field=models.JSONField(blank=True, default=list, help_text='5-bracket system from Luật 09/2026/QH16 (from 01/07/2026)'),
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='pit_dependent_deduction_2026',
            field=models.DecimalField(decimal_places=4, default=6200000, max_digits=15),
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='pit_personal_deduction_2026',
            field=models.DecimalField(decimal_places=4, default=15500000, max_digits=15),
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='ttdb_alcohol_high',
            field=models.DecimalField(decimal_places=4, default=0.65, max_digits=6),
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='ttdb_alcohol_low',
            field=models.DecimalField(decimal_places=4, default=0.35, max_digits=6),
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='ttdb_beer',
            field=models.DecimalField(decimal_places=4, default=0.65, max_digits=6),
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='ttdb_car_hybrid_discount',
            field=models.DecimalField(decimal_places=4, default=0.7, max_digits=6),
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='ttdb_car_under_9',
            field=models.DecimalField(decimal_places=4, default=0.15, max_digits=6),
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='ttdb_tobacco_absolute',
            field=models.DecimalField(decimal_places=4, default=5000, max_digits=15),
        ),
        migrations.AddField(
            model_name='taxrateconfig',
            name='ttdb_tobacco_rate',
            field=models.DecimalField(decimal_places=4, default=0.75, max_digits=6),
        ),
    ]
