# Generated by Django 5.2.15 on 2026-06-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_taxtype_taxrateconfig_fct_cit_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PITRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(blank=True, null=True)),
                ('personal_deduction', models.DecimalField(decimal_places=4, max_digits=15)),
                ('dependent_deduction', models.DecimalField(decimal_places=4, max_digits=15)),
                ('brackets', models.JSONField(default=list)),
                ('legal_basis', models.CharField(max_length=200)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'PIT Rate History',
                'verbose_name_plural': 'PIT Rate History',
                'db_table': 'pit_rate_history',
                'ordering': ['-period_start'],
            },
        ),
    ]
