# Generated by Django 5.2.15 on 2026-06-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pit_history_and_bidding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrateconfig',
            name='pit_dependent_deduction',
            field=models.DecimalField(decimal_places=4, default=5200000, max_digits=15),
        ),
        migrations.AlterField(
            model_name='taxrateconfig',
            name='pit_personal_deduction',
            field=models.DecimalField(decimal_places=4, default=13200000, max_digits=15),
        ),
    ]
