# Generated by Django 5.2.15 on 2026-07-10 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_featureflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50)),
                ('score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_affinities', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_affinities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_search_affinity',
                'indexes': [models.Index(fields=['user', 'company'], name='user_search_user_id_40c2d9_idx')],
                'unique_together': {('user', 'company', 'object_type')},
            },
        ),
    ]
