# Generated by Django 5.2.15 on 2026-07-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_usersearchaffinity"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("doanh_nghiep_sieu_nho", "Doanh nghiệp siêu nhỏ"),
                    ("ho_kinh_doanh", "Hộ kinh doanh"),
                    ("ca_nhan_kinh_doanh", "Cá nhân kinh doanh"),
                ],
                default="doanh_nghiep_sieu_nho",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="tndn_method",
            field=models.CharField(
                choices=[("tinh_thue", "Tính thuế"), ("ty_le_phan_tram", "Tỷ lệ %")],
                default="tinh_thue",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="vat_method",
            field=models.CharField(
                choices=[("khau_tru", "Khấu trừ"), ("ty_le_phan_tram", "Tỷ lệ %")],
                default="khau_tru",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="accounting_regime",
            field=models.CharField(
                choices=[
                    ("tt133", "TT133/2016 (DN nhỏ và vừa)"),
                    ("tt200", "TT200/2014 (DN lớn)"),
                    ("q48", "QĐ48/2006 (cũ)"),
                    ("tt58", "TT58/2026 (DN siêu nhỏ)"),
                ],
                default="tt133",
                max_length=10,
            ),
        ),
    ]
