# Generated by Django 5.2.15 on 2026-07-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_company_enabled_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxrateconfig",
            name="pit_dependent_income_threshold",
            field=models.DecimalField(decimal_places=4, default=3000000, max_digits=15),
        ),
        migrations.AddField(
            model_name="taxrateconfig",
            name="pit_education_deduction",
            field=models.DecimalField(
                decimal_places=4, default=24000000, max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="taxrateconfig",
            name="pit_meal_allowance",
            field=models.DecimalField(decimal_places=4, default=1200000, max_digits=15),
        ),
        migrations.AddField(
            model_name="taxrateconfig",
            name="pit_medical_deduction",
            field=models.DecimalField(
                decimal_places=4, default=23000000, max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="taxrateconfig",
            name="pit_pension_allowance",
            field=models.DecimalField(decimal_places=4, default=3000000, max_digits=15),
        ),
        migrations.AddField(
            model_name="taxrateconfig",
            name="pit_withholding_threshold",
            field=models.DecimalField(decimal_places=4, default=5000000, max_digits=15),
        ),
    ]
