# Generated by Django 5.2.15 on 2026-07-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_taxrateconfig_pit_dependent_income_threshold_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxrateconfig",
            name="base_salary",
        ),
        migrations.AddField(
            model_name="taxrateconfig",
            name="bhxh_base_salary",
            field=models.DecimalField(decimal_places=4, default=2530000, max_digits=15),
        ),
        migrations.AlterField(
            model_name="taxrateconfig",
            name="bhxh_cap",
            field=models.DecimalField(
                decimal_places=4, default=50600000, max_digits=15
            ),
        ),
    ]
