# Generated by Django 5.2.15 on 2026-07-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_bhxh_rates_nd161"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxrateconfig",
            name="cit_exemption_threshold",
            field=models.DecimalField(decimal_places=4, default=1000000000, max_digits=20),
        ),
    ]
