# Generated by Django 5.2.15 on 2026-07-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_vat_thresholds_luat_gtgt_09_2026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="accounting_regime",
            field=models.CharField(
                choices=[
                    ("tt133", "TT133/2016 (DN nhỏ và vừa)"),
                    ("tt200", "TT200/2014 (DN lớn)"),
                    ("q48", "QĐ48/2006 (cũ — deprecated, khuyến nghị không dùng)"),
                    ("tt58", "TT58/2026 (DN siêu nhỏ)"),
                ],
                default="tt133",
                max_length=10,
            ),
        ),
    ]
