# Generated by Django 5.2.16 on 2026-07-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_company_accounting_regime_q48_deprecated"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
