# Generated by Django 5.2.15 on 2026-06-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('balance_type', models.CharField(choices=[('debit', 'Nợ'), ('credit', 'Có')], max_length=10)),
                ('category', models.CharField(choices=[('asset', 'Tài sản'), ('liability', 'Nợ phải trả'), ('equity', 'Vốn chủ sở hữu'), ('revenue', 'Doanh thu'), ('expense', 'Chi phí'), ('other_income', 'Thu nhập khác'), ('other_expense', 'Chi phí khác'), ('off_balance', 'Ngoài bảng')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'account_type',
                'ordering': ['code'],
            },
        ),
    ]
