# Generated by Django 5.2.15 on 2026-06-17 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('account_name_en', models.CharField(blank=True, max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('parent_account_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('account_level', models.PositiveSmallIntegerField(default=1)),
                ('is_posting_account', models.BooleanField(default=False, help_text='Có cho phép hạch toán trực tiếp?')),
                ('is_general_ledger_account', models.BooleanField(default=False, help_text='Là tài khoản sổ cái?')),
                ('is_active', models.BooleanField(default=True)),
                ('allows_object_code', models.BooleanField(default=False)),
                ('allows_cost_center', models.BooleanField(default=False)),
                ('allows_project', models.BooleanField(default=False)),
                ('allows_production_order', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='master_data.accounttype')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.company')),
            ],
            options={
                'db_table': 'chart_of_accounts',
                'ordering': ['account_code'],
                'indexes': [models.Index(fields=['company', 'parent_account_code'], name='chart_of_ac_company_6aee6e_idx'), models.Index(fields=['company', 'is_active'], name='chart_of_ac_company_ff0746_idx')],
                'unique_together': {('company', 'account_code')},
            },
        ),
    ]
