# Generated by Django 5.2.15 on 2026-06-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_chartofaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='parent_account_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
