# Generated by Django 5.2.15 on 2026-06-17 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('master_data', '0003_alter_chartofaccounts_parent_account_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('short_name', models.CharField(blank=True, default='', max_length=100)),
                ('tax_code', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_group_code', models.CharField(blank=True, default='', max_length=50)),
                ('sales_staff_code', models.CharField(blank=True, default='', max_length=50)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('default_vat_rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=6)),
                ('gl_account_receivable', models.CharField(default='131', max_length=20)),
                ('is_supplier', models.BooleanField(default=False, help_text='Also a vendor?')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.company')),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='customer_company_2b10eb_idx'), models.Index(fields=['tax_code'], name='customer_tax_cod_ce7b04_idx')],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('short_name', models.CharField(blank=True, default='', max_length=100)),
                ('tax_code', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('vendor_group_code', models.CharField(blank=True, default='', max_length=50)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=100)),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('gl_account_payable', models.CharField(default='331', max_length=20)),
                ('is_supplier', models.BooleanField(default=True)),
                ('is_contractor', models.BooleanField(default=False, help_text='Cung cấp dịch vụ?')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='core.company')),
            ],
            options={
                'db_table': 'vendor',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='vendor_company_9623fa_idx'), models.Index(fields=['tax_code'], name='vendor_tax_cod_6429b9_idx')],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
