# Generated by Django 5.2.15 on 2026-06-17 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('master_data', '0004_customer_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('name_en', models.CharField(blank=True, default='', max_length=500)),
                ('barcode', models.CharField(blank=True, default='', max_length=50)),
                ('product_type', models.CharField(choices=[('raw_material', 'Nguyên vật liệu'), ('semi_finished', 'Bán thành phẩm'), ('finished', 'Thành phẩm'), ('goods', 'Hàng hóa'), ('supplies', 'Vật tư'), ('tool', 'CCDC'), ('service', 'Dịch vụ')], max_length=20)),
                ('unit_id', models.CharField(max_length=20)),
                ('product_group_code', models.CharField(blank=True, default='', max_length=50)),
                ('weight', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('cost_method', models.CharField(choices=[('weighted_avg', 'Bình quân gia quyền'), ('moving_avg', 'Bình quân di động'), ('fifo', 'Nhập trước xuất trước')], default='weighted_avg', max_length=20)),
                ('gl_account_inv', models.CharField(max_length=20)),
                ('gl_account_cogs', models.CharField(max_length=20)),
                ('gl_account_revenue', models.CharField(max_length=20)),
                ('default_vat_rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=6)),
                ('default_unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('min_stock', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('max_stock', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.company')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='product_company_b103d7_idx'), models.Index(fields=['barcode'], name='product_barcode_d2887e_idx')],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('warehouse_type', models.CharField(choices=[('material', 'Kho nguyên vật liệu'), ('finished', 'Kho thành phẩm'), ('transit', 'Kho chuyển hàng'), ('virtual', 'Kho ảo')], default='material', max_length=20)),
                ('manager_code', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('gl_account', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.company')),
            ],
            options={
                'db_table': 'warehouse',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
