# Generated by Django 5.2.15 on 2026-07-04 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_productprice_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceGroup',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name_vi', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('default_tax_account_debit', models.CharField(blank=True, max_length=20)),
                ('default_tax_account_credit', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_data_invoicegroup',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TaxRateCode',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tỷ lệ thuế GTGT (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_data_taxratecode',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
