# Generated by Django 5.2.15 on 2026-07-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_invoicegroup_taxratecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='exchange_rate_method_credit',
            field=models.CharField(choices=[('NONE', 'Không áp dụng'), ('AVG', 'Bình quân'), ('ENDING', 'Cuối kỳ'), ('SPOT', 'Giao dịch')], default='NONE', help_text='Phương pháp tính tỷ giá cho bên Có', max_length=10),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='exchange_rate_method_debit',
            field=models.CharField(choices=[('NONE', 'Không áp dụng'), ('AVG', 'Bình quân'), ('ENDING', 'Cuối kỳ'), ('SPOT', 'Giao dịch')], default='NONE', help_text='Phương pháp tính tỷ giá cho bên Nợ', max_length=10),
        ),
    ]
