# Generated by Django 5.2.15 on 2026-06-17 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ledger', '0002_accountperiodbalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('print_template', 'In từ hệ thống'), ('scanned_upload', 'Scan/Upload'), ('external', 'File ngoài'), ('signed_contract', 'Hợp đồng đã ký')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('file_type', models.CharField(blank=True, default='', max_length=10)),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('printed', 'Đã in'), ('signed', 'Đã ký'), ('scanned', 'Đã scan'), ('archived', 'Lưu trữ')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ledger.accountingvoucher')),
            ],
            options={
                'db_table': 'voucher_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'voucher'], name='voucher_doc_company_ee2d73_idx'), models.Index(fields=['company', 'document_type'], name='voucher_doc_company_3de64f_idx')],
            },
        ),
    ]
