# Generated by Django 5.2.15 on 2026-06-19 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_alter_taxrateconfig_pit_dependent_deduction_and_more'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('file_type', models.CharField(blank=True, default='', max_length=10)),
                ('file_size', models.BigIntegerField(default=0)),
                ('attachment_type', models.CharField(choices=[('specification', 'Thông số kỹ thuật'), ('contract_scan', 'Hợp đồng scan'), ('proposal', 'Báo giá/Proposal'), ('report', 'Báo cáo'), ('certificate', 'Chứng chỉ'), ('photo', 'Ảnh/Hình'), ('deliverable', 'Sản phẩm bàn giao'), ('sla', 'Thỏa thuận SLA'), ('invoice_scan', 'Hóa đơn scan'), ('receipt', 'Biên lai'), ('other', 'Khác')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Đã tải lên'), ('verified', 'Đã kiểm tra'), ('archived', 'Lưu trữ')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='attachment_content_8a9d12_idx')],
            },
        ),
    ]
