# Generated by Django 5.2.15 on 2026-06-17 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('service_func', models.CharField(help_text='Dotted path: apps.recurring.runners.run_depreciation', max_length=255)),
                ('schedule_type', models.CharField(choices=[('monthly', 'Hàng tháng'), ('quarterly', 'Hàng quý'), ('yearly', 'Hàng năm')], default='monthly', max_length=20)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='Day of month to run on (1-28)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_result', models.JSONField(blank=True, default=dict)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates', to='core.company')),
            ],
            options={
                'verbose_name': 'Bút toán định kỳ',
                'verbose_name_plural': 'Bút toán định kỳ',
                'db_table': 'recurring_template',
                'ordering': ['schedule_type', 'day_of_month', 'id'],
                'indexes': [models.Index(fields=['company', 'is_active', 'next_run_at'], name='recurring_t_company_2eb553_idx')],
            },
        ),
    ]
