# Generated by Django 5.2.15 on 2026-06-22 15:50

import apps.core.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_alter_taxrateconfig_pit_dependent_deduction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('object_label', models.CharField(max_length=255)),
                ('voucher_type', models.CharField(blank=True, default='', max_length=30)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(max_length=30)),
                ('min_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('max_amount', models.DecimalField(decimal_places=4, default=999999999999, max_digits=20)),
                ('approver_roles', models.JSONField(default=list)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'db_table': 'approval_rule',
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('role_required', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps_done', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps_assigned', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalrequest')),
            ],
            options={
                'db_table': 'approval_step',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['company', 'status'], name='approval_re_company_8feae7_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='approval_re_content_3a0cfc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalrule',
            unique_together={('company', 'voucher_type', 'min_amount')},
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('request', 'sequence')},
        ),
    ]
