# Generated by Django 5.2.15 on 2026-06-25 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#2563eb', max_length=7)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Danh mục blog',
                'verbose_name_plural': 'Danh mục blog',
                'db_table': 'blog_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('excerpt', models.TextField(blank=True, default='', help_text='Tóm tắt ngắn — hiển thị ở list')),
                ('content', models.TextField(help_text='Markdown hoặc HTML')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/')),
                ('tags', models.CharField(blank=True, default='', help_text='Phân cách bằng dấu phẩy', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã đăng')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='public.blogcategory')),
            ],
            options={
                'db_table': 'blog_article',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='blog_articl_status_47bfec_idx'), models.Index(fields=['category', '-published_at'], name='blog_articl_categor_a7f6aa_idx'), models.Index(fields=['slug'], name='blog_articl_slug_cc8df7_idx')],
            },
        ),
    ]
