# Generated by Django 5.2.15 on 2026-06-25 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('company_size', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('landing', 'Landing page'), ('blog', 'Blog'), ('pricing', 'Pricing page'), ('demo', 'Demo request'), ('contact', 'Contact form')], default='landing', max_length=20)),
                ('referrer_url', models.URLField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('contacted', 'Đã liên hệ'), ('converted', 'Đã chuyển đổi'), ('rejected', 'Từ chối')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('crm_lead_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(default='landing', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'newsletter_subscriber',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='blogarticle',
            name='blog_articl_status_47bfec_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogarticle',
            name='blog_articl_categor_a7f6aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogarticle',
            name='blog_articl_slug_cc8df7_idx',
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='content',
            field=models.TextField(help_text='HTML content'),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['status', '-created_at'], name='contact_req_status_4782dc_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['source'], name='contact_req_source_03712e_idx'),
        ),
    ]
