# Generated by Django 5.2.15 on 2026-06-17 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, default='', max_length=50)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('seller_tax_code', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('seller_name', models.CharField(blank=True, default='', max_length=255)),
                ('seller_address', models.TextField(blank=True, default='')),
                ('amount_before_vat', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('vat_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('scanned_file', models.FileField(blank=True, null=True, upload_to='input_invoices/')),
                ('einvoice_xml', models.TextField(blank=True, default='')),
                ('extraction_status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('extracted', 'Đã trích xuất'), ('matched', 'Đã khớp'), ('excluded', 'Loại trừ')], db_index=True, default='pending', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_invoices', to='core.company')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_input_invoices', to=settings.AUTH_USER_MODEL)),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_sources', to='purchasing.purchaseinvoice')),
            ],
            options={
                'verbose_name': 'Hóa đơn đầu vào',
                'verbose_name_plural': 'Hóa đơn đầu vào',
                'db_table': 'input_invoice',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'extraction_status'], name='input_invoi_company_50a7bd_idx'), models.Index(fields=['seller_tax_code'], name='input_invoi_seller__0dda35_idx')],
            },
        ),
    ]
