# Generated by Django 5.2.15 on 2026-06-17 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ledger', '0002_accountperiodbalance'),
        ('master_data', '0005_product_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('receipt', 'Phiếu nhập'), ('issue', 'Phiếu xuất'), ('transfer', 'Phiếu chuyển')], max_length=20)),
                ('voucher_no', models.CharField(max_length=50)),
                ('voucher_date', models.DateField()),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.PositiveSmallIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_vouchers', to='core.company')),
                ('gl_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_vouchers', to='ledger.accountingvoucher')),
                ('to_warehouse', models.ForeignKey(blank=True, help_text='Destination warehouse for transfer only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='master_data.warehouse')),
                ('warehouse', models.ForeignKey(help_text='Source warehouse for receipt/issue; from-warehouse for transfer.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_vouchers', to='master_data.warehouse')),
            ],
            options={
                'db_table': 'stock_voucher',
                'ordering': ['-voucher_date', '-id'],
                'unique_together': {('company', 'voucher_type', 'voucher_no')},
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('avg_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('last_transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger', to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger', to='master_data.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger', to='master_data.warehouse')),
            ],
            options={
                'db_table': 'stock_ledger',
                'indexes': [models.Index(fields=['product', 'warehouse'], name='stock_ledge_product_2624a7_idx')],
                'unique_together': {('company', 'product', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='StockVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_id', models.CharField(default='CAI', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lines', to='master_data.product')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockvoucher')),
            ],
            options={
                'db_table': 'stock_voucher_line',
                'ordering': ['line_no'],
                'unique_together': {('voucher', 'line_no')},
            },
        ),
    ]
