# Generated by Django 5.2.15 on 2026-06-19 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_taxrateconfig_pit_dependent_deduction_and_more'),
        ('inventory', '0001_initial'),
        ('master_data', '0006_productprice_productvariant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_no', models.CharField(max_length=50)),
                ('adjustment_date', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='master_data.warehouse')),
            ],
            options={
                'db_table': 'stock_adjustment',
                'ordering': ['-adjustment_date'],
                'unique_together': {('company', 'adjustment_no')},
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('counted_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('difference', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockadjustment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustment_lines', to='master_data.product')),
            ],
            options={
                'db_table': 'stock_adjustment_line',
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Tồn thấp'), ('overstock', 'Tồn cao'), ('expiring', 'Gần hết hạn')], max_length=20)),
                ('current_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('threshold', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='master_data.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.warehouse')),
            ],
            options={
                'db_table': 'stock_alert',
            },
        ),
    ]
