# Generated by Django 5.2.15 on 2026-06-19 05:17

import apps.core.managers
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_alter_taxrateconfig_pit_dependent_deduction_and_more'),
        ('master_data', '0005_product_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('campaign_type', models.CharField(choices=[('email', 'Email marketing'), ('social', 'Mạng xã hội'), ('event', 'Sự kiện'), ('webinar', 'Webinar'), ('ads', 'Quảng cáo'), ('other', 'Khác')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Lưu nháp'), ('active', 'Đang chạy'), ('paused', 'Tạm dừng'), ('completed', 'Hoàn thành')], default='draft', max_length=20)),
                ('budget', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('actual_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'db_table': 'crm_campaign',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'code')},
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='CRMAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('tax_code', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_accounts', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_accounts', to='master_data.customer')),
            ],
            options={
                'db_table': 'crm_account',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='CRMContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('mobile', models.CharField(blank=True, default='', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_decision_maker', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.crmaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'db_table': 'crm_contact',
                'ordering': ['-is_primary', 'full_name'],
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='CRMLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('mobile', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('tax_code', models.CharField(blank=True, default='', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Giới thiệu'), ('campaign', 'Chiến dịch'), ('cold_call', 'Gọi điện'), ('event', 'Sự kiện'), ('other', 'Khác')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Mới'), ('contacted', 'Đã liên hệ'), ('qualified', 'Đủ điều kiện'), ('converted', 'Đã chuyển đổi'), ('rejected', 'Từ chối')], default='new', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('converted_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='crm.crmaccount')),
            ],
            options={
                'db_table': 'crm_lead',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('stage', models.CharField(choices=[('prospecting', 'Tìm kiếm (10%)'), ('qualification', 'Đánh giá (25%)'), ('proposal', 'Báo giá (50%)'), ('negotiation', 'Đàm phán (75%)'), ('won', 'Thắng (100%)'), ('lost', 'Thua (0%)')], default='prospecting', max_length=20)),
                ('probability', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5)),
                ('estimated_value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('loss_reason', models.TextField(blank=True, default='')),
                ('created_contract_id', models.BigIntegerField(blank=True, null=True)),
                ('created_project_id', models.BigIntegerField(blank=True, null=True)),
                ('created_invoice_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.crmaccount')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.crmcontact')),
            ],
            options={
                'db_table': 'crm_opportunity',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'code')},
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.08'), max_digits=6)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crm.opportunity')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.product')),
            ],
            options={
                'db_table': 'crm_opportunity_line',
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('customer_code', models.CharField(blank=True, default='', max_length=50)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('normal', 'Bình thường'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Mở'), ('in_progress', 'Đang xử lý'), ('resolved', 'Đã giải quyết'), ('closed', 'Đã đóng')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('related_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.opportunity')),
            ],
            options={
                'db_table': 'crm_ticket',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'code')},
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Gọi điện'), ('meeting', 'Họp'), ('email', 'Email'), ('task', 'Nhiệm vụ'), ('note', 'Ghi chú'), ('visit', 'Thăm khách')], max_length=20)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planned', 'Lên kế hoạch'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='planned', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.crmaccount')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.crmlead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.opportunity')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.ticket')),
            ],
            options={
                'db_table': 'crm_activity',
                'ordering': ['-scheduled_at'],
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='crm.ticket')),
            ],
            options={
                'db_table': 'crm_ticket_response',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status', models.CharField(choices=[('sent', 'Đã gửi'), ('opened', 'Đã mở'), ('clicked', 'Đã click'), ('replied', 'Đã phản hồi'), ('converted', 'Đã chuyển đổi'), ('bounced', 'Bounce')], default='sent', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crm.campaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to='crm.crmcontact')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to='crm.crmlead')),
            ],
            options={
                'db_table': 'crm_campaign_member',
                'unique_together': {('campaign', 'contact'), ('campaign', 'lead')},
            },
        ),
    ]
