# Generated by Django 5.2.15 on 2026-06-17 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hr_position',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('manager_code', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hr.department')),
            ],
            options={
                'db_table': 'hr_department',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='male', max_length=10)),
                ('id_card_no', models.CharField(blank=True, default='', max_length=20)),
                ('id_card_date', models.DateField(blank=True, null=True)),
                ('id_card_place', models.CharField(blank=True, default='', max_length=255)),
                ('personal_tax_code', models.CharField(blank=True, default='', max_length=20)),
                ('social_insurance_no', models.CharField(blank=True, default='', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('hire_date', models.DateField()),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('official_date', models.DateField(blank=True, null=True)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('base_salary', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('allowance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('bank_account_no', models.CharField(blank=True, default='', max_length=50)),
                ('bank_id', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Đang làm việc'), ('on_leave', 'Nghỉ phép'), ('resigned', 'Đã nghỉ việc')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.position')),
            ],
            options={
                'db_table': 'hr_employee',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['company', 'status'], name='hr_employee_company_9e19fb_idx'), models.Index(fields=['company', 'is_active'], name='hr_employee_company_77ce24_idx')],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
