# Generated by Django 5.2.15 on 2026-06-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('spouse', 'Vợ/Chồng'), ('child', 'Con'), ('father', 'Cha'), ('mother', 'Mẹ'), ('other', 'Khác')], max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('id_card_no', models.CharField(blank=True, default='', max_length=20)),
                ('tax_code', models.CharField(blank=True, default='', max_length=20)),
                ('deduction_amount', models.DecimalField(decimal_places=4, default=4400000, max_digits=20)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('registration_status', models.CharField(choices=[('pending', 'Chờ đăng ký'), ('registered', 'Đã đăng ký'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_dependent',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='LaborContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=50)),
                ('contract_type', models.CharField(choices=[('probation', 'Thử việc'), ('fixed_term', 'Xác định thời hạn'), ('indefinite', 'Không xác định thời hạn'), ('seasonal', 'Mùa vụ / Công việc cụ thể')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('salary_base', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('salary_gross', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('allowance_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('insurance_salary_base', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('join_insurance', models.BooleanField(default=True)),
                ('position_title', models.CharField(blank=True, default='', max_length=255)),
                ('work_location', models.CharField(blank=True, default='', max_length=255)),
                ('signing_date', models.DateField(blank=True, null=True)),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='contracts/labor/')),
                ('status', models.CharField(choices=[('draft', 'Lưu nháp'), ('active', 'Đang hiệu lực'), ('expired', 'Đã hết hạn'), ('terminated', 'Đã chấm dứt')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_contracts', to='core.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_contracts', to='hr.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_contracts', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_labor_contract',
                'ordering': ['-start_date'],
                'unique_together': {('company', 'contract_no')},
            },
        ),
    ]
