# Generated by Django 5.2.15 on 2026-06-17 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hr', '0002_dependent_laborcontract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Nghỉ phép năm'), ('sick', 'Nghỉ ốm đau'), ('maternity', 'Thai sản'), ('marriage', 'Kết hôn'), ('funeral', 'Tang chế'), ('unpaid', 'Nghỉ không lương')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('maternity_months', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_leave_record',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('salary_base', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('bhxh_employee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('bhyt_employee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('bhtn_employee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_employee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('bhxh_employer', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('bhyt_employer', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('bhtn_employer', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('bhtnld_employer', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('kpcd_employer', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_employer', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_contributions', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_contributions', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_insurance_contribution',
                'ordering': ['-period'],
                'unique_together': {('employee', 'period')},
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.SmallIntegerField()),
                ('standard_days', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_leave_balance',
                'unique_together': {('employee', 'fiscal_year')},
            },
        ),
    ]
