# Generated by Django 5.2.15 on 2026-07-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_dependent_deduction_2026"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="meal_allowance",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="employee",
            name="pension_allowance",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
