# Generated by Django 5.2.15 on 2026-06-17 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.SmallIntegerField()),
                ('period', models.PositiveSmallIntegerField()),
                ('voucher_no', models.CharField(max_length=50)),
                ('voucher_type', models.CharField(choices=[('journal', 'Phiếu kế toán'), ('cash_receipt', 'Phiếu thu'), ('cash_payment', 'Phiếu chi'), ('sales_invoice', 'Hóa đơn bán'), ('purchase_invoice', 'Phiếu nhập mua'), ('stock_voucher', 'Phiếu nhập xuất'), ('depreciation', 'Khấu hao'), ('allocation', 'Phân bổ'), ('closing', 'Kết chuyển')], max_length=30)),
                ('voucher_date', models.DateField()),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('book_code', models.CharField(blank=True, max_length=20)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Lưu tạm'), (1, 'Ghi sổ phụ'), (2, 'Ghi sổ cái'), (3, 'Đã khóa')], default=2)),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('total_fc', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_vnd', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('source_reference_id', models.BigIntegerField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_created', to=settings.AUTH_USER_MODEL)),
                ('reversal_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='ledger.accountingvoucher')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_voucher',
                'ordering': ['-voucher_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('account_code', models.CharField(max_length=20)),
                ('object_type', models.CharField(blank=True, choices=[('', '—'), ('customer', 'Khách hàng'), ('vendor', 'Nhà cung cấp'), ('employee', 'Nhân viên'), ('bank', 'Ngân hàng'), ('other', 'Khác')], default='', max_length=20)),
                ('object_code', models.CharField(blank=True, default='', max_length=50)),
                ('object_name', models.CharField(blank=True, default='', max_length=255)),
                ('debit_fc', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('credit_fc', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('debit_vnd', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('credit_vnd', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('description', models.TextField(blank=True, default='')),
                ('cost_center_code', models.CharField(blank=True, default='', max_length=50)),
                ('project_code', models.CharField(blank=True, default='', max_length=50)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.accountingvoucher')),
            ],
            options={
                'db_table': 'voucher_line',
                'ordering': ['line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='accountingvoucher',
            index=models.Index(fields=['company', 'voucher_date'], name='accounting__company_97c9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingvoucher',
            index=models.Index(fields=['company', 'fiscal_year', 'period', 'status'], name='accounting__company_1ffb93_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingvoucher',
            index=models.Index(fields=['company', 'voucher_type', 'voucher_date'], name='accounting__company_00135f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountingvoucher',
            unique_together={('company', 'fiscal_year', 'voucher_type', 'voucher_no')},
        ),
        migrations.AddIndex(
            model_name='voucherline',
            index=models.Index(fields=['account_code'], name='voucher_lin_account_656b18_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherline',
            index=models.Index(fields=['object_type', 'object_code'], name='voucher_lin_object__657952_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='voucherline',
            unique_together={('voucher', 'line_no')},
        ),
    ]
