# Generated by Django 5.2.15 on 2026-06-17 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPeriodBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.SmallIntegerField()),
                ('period', models.PositiveSmallIntegerField()),
                ('account_code', models.CharField(max_length=20)),
                ('object_type', models.CharField(blank=True, default='', max_length=20)),
                ('object_code', models.CharField(blank=True, default='', max_length=50)),
                ('opening_debit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('opening_credit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('period_debit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('period_credit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('closing_debit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('closing_credit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('opening_debit_fc', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('opening_credit_fc', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('period_debit_fc', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('period_credit_fc', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('closing_debit_fc', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('closing_credit_fc', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('last_transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='core.company')),
            ],
            options={
                'db_table': 'account_period_balance',
                'indexes': [models.Index(fields=['company', 'fiscal_year', 'period'], name='account_per_company_d3ac90_idx'), models.Index(fields=['account_code'], name='account_per_account_c2538d_idx'), models.Index(fields=['object_type', 'object_code'], name='account_per_object__2c4663_idx')],
                'unique_together': {('company', 'fiscal_year', 'period', 'account_code', 'object_type', 'object_code')},
            },
        ),
    ]
