# Generated by Django 5.2.15 on 2026-07-04 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_accountperiodbalance'),
        ('master_data', '0007_invoicegroup_taxratecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherline',
            name='goods_amount_vnd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='invoice_form',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='invoice_group_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_lines', to='master_data.invoicegroup'),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='invoice_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='invoice_serial',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='invoice_symbol',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='object_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='offset_account_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='tax_amount_vnd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_lines', to='master_data.taxratecode'),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
