# Generated by Django 5.2.15 on 2026-07-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_voucherline_goods_amount_vnd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherline',
            name='is_auto_tax_posting',
            field=models.BooleanField(default=False, help_text='True nếu dòng này được VoucherPostingService tự động tạo cho TK 1331/33311'),
        ),
    ]
