# Generated by Django 5.2.15 on 2026-07-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_tt58_company_fields"),
        ("ledger", "0005_voucherline_running_balances"),
    ]

    operations = [
        migrations.CreateModel(
            name="DnsnVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.SmallIntegerField()),
                ("period", models.PositiveSmallIntegerField()),
                ("voucher_no", models.CharField(max_length=50)),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("phieu_thu", "Phiếu thu"),
                            ("phieu_chi", "Phiếu chi"),
                            ("phieu_nhap", "Phiếu nhập"),
                            ("phieu_xuat", "Phiếu xuất"),
                            ("hoa_don_ban_hang", "Hóa đơn bán hàng"),
                            ("hoa_don_mua_hang", "Hóa đơn mua hàng"),
                            ("chung_tu_khac", "Chứng từ khác"),
                        ],
                        max_length=30,
                    ),
                ),
                ("voucher_date", models.DateField()),
                ("posting_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "partner_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "partner_tax_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "partner_address",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("invoice_no", models.CharField(blank=True, default="", max_length=50)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                (
                    "invoice_form",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "invoice_serial",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Lưu tạm"),
                            ("posted", "Đã ghi sổ"),
                            ("locked", "Đã khóa"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dnsn_vouchers",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "dnsn_voucher",
                "ordering": ["-voucher_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DnsnLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.SmallIntegerField()),
                ("period", models.PositiveSmallIntegerField()),
                ("line_no", models.PositiveSmallIntegerField()),
                ("entry_date", models.DateField()),
                (
                    "ledger_type",
                    models.CharField(
                        choices=[
                            ("s1", "S1-DNSN (Sổ doanh thu — Nhóm 1)"),
                            ("s2a", "S2a-DNSN (Sổ doanh thu — Nhóm 2)"),
                            ("s2b", "S2b-DNSN (Sổ chi tiết doanh thu, chi phí)"),
                            ("s2c", "S2c-DNSN (Sổ vật liệu, hàng hóa)"),
                            ("s2d", "S2d-DNSN (Sổ chi tiết tiền)"),
                            ("s3a", "S3a-DNSN (Sổ doanh thu — Nhóm 3)"),
                            ("s3b", "S3b-DNSN (Sổ nghĩa vụ thuế GTGT)"),
                            ("s4a", "S4a-DNSN (Sổ công nợ — tùy chọn)"),
                            ("s4b", "S4b-DNSN (Sổ TSCĐ — tùy chọn)"),
                            ("s4c", "S4c-DNSN (Sổ thuế khác — tùy chọn)"),
                            ("s4d", "S4d-DNSN (Sổ vốn CSH — tùy chọn)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "partner_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "revenue_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "cost_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "tndn_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "cash_in",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "cash_out",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "bank_in",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "bank_out",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "vat_input",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "vat_output",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "vat_payable",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("item_code", models.CharField(blank=True, default="", max_length=50)),
                ("item_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "running_balance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dnsn_ledger_entries",
                        to="core.company",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="ledger.dnsnvoucher",
                    ),
                ),
            ],
            options={
                "db_table": "dnsn_ledger_entry",
                "ordering": ["entry_date", "id", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="DnsnLedgerBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.SmallIntegerField()),
                ("period", models.PositiveSmallIntegerField()),
                (
                    "ledger_type",
                    models.CharField(
                        choices=[
                            ("s1", "S1-DNSN (Sổ doanh thu — Nhóm 1)"),
                            ("s2a", "S2a-DNSN (Sổ doanh thu — Nhóm 2)"),
                            ("s2b", "S2b-DNSN (Sổ chi tiết doanh thu, chi phí)"),
                            ("s2c", "S2c-DNSN (Sổ vật liệu, hàng hóa)"),
                            ("s2d", "S2d-DNSN (Sổ chi tiết tiền)"),
                            ("s3a", "S3a-DNSN (Sổ doanh thu — Nhóm 3)"),
                            ("s3b", "S3b-DNSN (Sổ nghĩa vụ thuế GTGT)"),
                            ("s4a", "S4a-DNSN (Sổ công nợ — tùy chọn)"),
                            ("s4b", "S4b-DNSN (Sổ TSCĐ — tùy chọn)"),
                            ("s4c", "S4c-DNSN (Sổ thuế khác — tùy chọn)"),
                            ("s4d", "S4d-DNSN (Sổ vốn CSH — tùy chọn)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "opening_revenue",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "period_revenue",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "closing_revenue",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "opening_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "period_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "closing_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "opening_vat",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "period_vat",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "closing_vat",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "opening_cash",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "period_cash",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "closing_cash",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("last_transaction_date", models.DateField(blank=True, null=True)),
                ("transaction_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dnsn_ledger_balances",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "dnsn_ledger_balance",
                "indexes": [
                    models.Index(
                        fields=["company", "fiscal_year", "period"],
                        name="dnsn_ledger_company_10ec2a_idx",
                    ),
                    models.Index(
                        fields=["ledger_type"], name="dnsn_ledger_ledger__c72e47_idx"
                    ),
                ],
                "unique_together": {
                    ("company", "fiscal_year", "period", "ledger_type")
                },
            },
        ),
        migrations.AddIndex(
            model_name="dnsnvoucher",
            index=models.Index(
                fields=["company", "voucher_date"],
                name="dnsn_vouche_company_8bb56a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dnsnvoucher",
            index=models.Index(
                fields=["company", "fiscal_year", "period", "status"],
                name="dnsn_vouche_company_de2da0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dnsnvoucher",
            index=models.Index(
                fields=["company", "voucher_type", "voucher_date"],
                name="dnsn_vouche_company_75d3a2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dnsnvoucher",
            unique_together={("company", "fiscal_year", "voucher_type", "voucher_no")},
        ),
        migrations.AddIndex(
            model_name="dnsnledgerentry",
            index=models.Index(
                fields=["company", "fiscal_year", "period", "ledger_type"],
                name="dnsn_ledger_company_a35142_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dnsnledgerentry",
            index=models.Index(
                fields=["company", "ledger_type", "entry_date"],
                name="dnsn_ledger_company_0baaa5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dnsnledgerentry",
            unique_together={("voucher", "line_no")},
        ),
    ]
