# Generated by Django 5.2.15 on 2026-06-17 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('type', 'Loại'), ('group', 'Nhóm'), ('subgroup', 'Phân nhóm')], max_length=20)),
                ('is_for_tool', models.BooleanField(default=False, help_text='TRUE=CCDC (TK 142/242), FALSE=TSCĐ (TK 211/214)')),
                ('default_gl_account', models.CharField(blank=True, default='', max_length=20)),
                ('default_depreciation_account', models.CharField(blank=True, default='', max_length=20)),
                ('default_expense_account', models.CharField(blank=True, default='', max_length=20)),
                ('default_depreciation_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('default_useful_life_months', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='core.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assets.assetcategory')),
            ],
            options={
                'db_table': 'asset_category',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AssetUsingDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('default_expense_account', models.CharField(default='642', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_departments', to='core.company')),
            ],
            options={
                'db_table': 'asset_using_department',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
