# Generated by Django 5.2.15 on 2026-06-17 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50)),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_name_en', models.CharField(blank=True, default='', max_length=255)),
                ('gl_account', models.CharField(help_text='TK tài sản (211/212/213 cho TSCĐ, 142/242 cho CCDC)', max_length=20)),
                ('depreciation_account', models.CharField(help_text='TK hao mòn/lũy kế (2141/2142/2143 cho TSCĐ, 142/242 cho CCDC)', max_length=20)),
                ('expense_account', models.CharField(default='642', help_text='TK chi phí (641/642/635)', max_length=20)),
                ('original_cost', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Đường thẳng'), ('declining_balance', 'Số dư giảm dần'), ('units_of_production', 'Theo sản lượng')], default='straight_line', max_length=30)),
                ('depreciation_rate', models.DecimalField(decimal_places=4, default=0, help_text='Tỷ lệ KH/năm (vd 0.20 = 20%/năm)', max_digits=8)),
                ('useful_life_months', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('salvage_value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('is_tool', models.BooleanField(default=False, help_text='TRUE=CCDC (TK 142/242), FALSE=TSCĐ (TK 211/214)')),
                ('status', models.CharField(choices=[('draft', 'Lưu tạm'), ('active', 'Đang dùng'), ('fully_depreciated', 'Đã khấu hao hết'), ('disposed', 'Đã thanh lý')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='core.company')),
                ('using_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetusingdepartment')),
            ],
            options={
                'db_table': 'fixed_asset',
                'ordering': ['asset_code'],
                'indexes': [models.Index(fields=['company', 'status'], name='fixed_asset_company_19c29b_idx'), models.Index(fields=['company', 'is_tool'], name='fixed_asset_company_368037_idx')],
                'unique_together': {('company', 'asset_code')},
            },
        ),
    ]
