# Generated by Django 5.2.15 on 2026-06-17 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_fixedasset'),
        ('ledger', '0002_accountperiodbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='YYYY-MM format', max_length=7)),
                ('depreciation_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('accumulated_depreciation_end', models.DecimalField(decimal_places=4, max_digits=20)),
                ('net_book_value_end', models.DecimalField(decimal_places=4, max_digits=20)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_history', to='assets.fixedasset')),
                ('gl_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_depreciations', to='ledger.accountingvoucher')),
            ],
            options={
                'db_table': 'asset_depreciation',
                'ordering': ['-period'],
                'unique_together': {('asset', 'period')},
            },
        ),
    ]
