# Generated by Django 5.2.15 on 2026-06-19 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetdepreciation'),
        ('core', '0007_alter_taxrateconfig_pit_dependent_deduction_and_more'),
        ('ledger', '0002_accountperiodbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=50)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('increase', 'Tăng tài sản'), ('decrease', 'Giảm tài sản'), ('transfer', 'Điều chuyển'), ('revaluation', 'Đánh giá lại'), ('disposal', 'Thanh lý')], max_length=20)),
                ('new_asset', models.BooleanField(default=False)),
                ('disposal_value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('disposal_reason', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='assets.fixedasset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_transactions', to='core.company')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transfers', to='assets.assetusingdepartment')),
                ('gl_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.accountingvoucher')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='assets.assetusingdepartment')),
            ],
            options={
                'db_table': 'asset_transaction',
                'ordering': ['-transaction_date'],
                'unique_together': {('company', 'transaction_no')},
            },
        ),
    ]
