# Generated by Django 5.2.15 on 2026-06-22 15:55

import apps.core.managers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_alter_taxrateconfig_pit_dependent_deduction_and_more'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('manual', 'Ký thủ công (file PDF)'), ('misa', 'MISA'), ('vnpt', 'VNPT-Invoice'), ('ehoadon', 'eHoadon (VNPT)'), ('bkav', 'BKAV'), ('viettel', 'Viettel-Invoice')], default='manual', max_length=20)),
                ('pattern', models.CharField(default='1C26T', max_length=50)),
                ('serial', models.CharField(default='', max_length=20)),
                ('form_symbol', models.CharField(default='01GTKT', max_length=10)),
                ('issue_place', models.CharField(blank=True, default='', max_length=100)),
                ('api_url', models.CharField(blank=True, default='', max_length=500)),
                ('api_username', models.CharField(blank=True, default='', max_length=100)),
                ('api_password', models.CharField(blank=True, default='', max_length=200)),
                ('api_token', models.CharField(blank=True, default='', max_length=500)),
                ('tax_branch_code', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'verbose_name': 'Cấu hình hóa đơn điện tử',
                'db_table': 'einvoice_config',
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='EInvoiceReportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('bc01', 'BC01 — Báo cáo tình hình sử dụng HĐĐT'), ('bc26', 'BC26 — Báo cáo HĐĐT định kỳ'), ('tb04', 'TB04 — Thông báo phát hành')], max_length=10)),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveSmallIntegerField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='einvoice/reports/')),
                ('invoice_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'einvoice_report_batch',
                'ordering': ['-period_year', '-period_month'],
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='EInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, default='', max_length=50)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('pattern', models.CharField(default='1C26T', max_length=50)),
                ('serial', models.CharField(default='', max_length=20)),
                ('buyer_name', models.CharField(blank=True, default='', max_length=255)),
                ('buyer_tax_code', models.CharField(blank=True, default='', max_length=20)),
                ('buyer_address', models.TextField(blank=True, default='')),
                ('buyer_bank_account', models.CharField(blank=True, default='', max_length=50)),
                ('seller_name', models.CharField(blank=True, default='', max_length=255)),
                ('seller_tax_code', models.CharField(blank=True, default='', max_length=20)),
                ('seller_address', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=6)),
                ('vat_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_in_words', models.TextField(blank=True, default='')),
                ('payment_method', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='einvoice/xml/')),
                ('json_file', models.FileField(blank=True, null=True, upload_to='einvoice/json/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='einvoice/pdf/')),
                ('status', models.CharField(choices=[('draft', 'Dự thảo'), ('issued', 'Đã phát hành'), ('adjusted', 'Đã điều chỉnh'), ('replaced', 'Đã thay thế'), ('cancelled', 'Đã hủy')], default='draft', max_length=20)),
                ('adjustment_type', models.CharField(blank=True, default='', help_text='adjust=Điều chỉnh, replace=Thay thế, cancel=Hủy', max_length=20)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='einvoices_issued', to=settings.AUTH_USER_MODEL)),
                ('replaces_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='einvoice.einvoice')),
                ('sales_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='einvoices', to='sales.salesinvoice')),
            ],
            options={
                'db_table': 'einvoice',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='einvoice_company_86cbe8_idx'), models.Index(fields=['company', 'issue_date'], name='einvoice_company_bc5586_idx'), models.Index(fields=['sales_invoice'], name='einvoice_sales_i_e4e3b6_idx')],
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
    ]
