# Generated by Django 5.2.15 on 2026-07-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("einvoice", "0002_einvoice_form_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="einvoice",
            name="invoice_category",
            field=models.CharField(
                choices=[
                    ("coded", "Có mã của CQT"),
                    ("uncoded", "Không có mã"),
                    ("cash_register", "Khởi tạo từ máy tính tiền"),
                ],
                default="coded",
                max_length=20,
            ),
        ),
    ]
