# Generated by Django 5.2.15 on 2026-06-22 17:22

import apps.core.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_alter_taxrateconfig_pit_dependent_deduction_and_more'),
        ('ledger', '0002_accountperiodbalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, default='', max_length=10)),
                ('decimals', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(default='VND', max_length=3)),
                ('rate_date', models.DateField(db_index=True)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('rate_type', models.CharField(default='VCB', max_length=20)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'db_table': 'exchange_rate',
                'ordering': ['-rate_date'],
                'unique_together': {('company', 'from_currency', 'to_currency', 'rate_date', 'rate_type')},
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='FxRevaluationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('valuation_date', models.DateField()),
                ('reference_rate', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Dự thảo'), ('posted', 'Đã ghi sổ'), ('reversed', 'Đã đảo ngược')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('gl_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_revaluations', to='ledger.accountingvoucher')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reversal_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_reversals', to='ledger.accountingvoucher')),
            ],
            options={
                'db_table': 'fx_revaluation_batch',
                'unique_together': {('company', 'period_year', 'period_month')},
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
    ]
