# Generated by Django 5.2.15 on 2026-06-22 16:04

import apps.core.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_pit_history_and_bidding'),
        ('core', '0007_alter_taxrateconfig_pit_dependent_deduction_and_more'),
        ('ledger', '0002_accountperiodbalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(max_length=50)),
                ('loan_type', models.CharField(choices=[('short_term', 'Ngắn hạn (< 1 năm)'), ('long_term', 'Dài hạn (≥ 1 năm)'), ('overdraft', 'Thấu chi')], default='short_term', max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account', models.CharField(blank=True, default='', max_length=50)),
                ('contract_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('interest_rate_pa', models.DecimalField(decimal_places=4, default=0.1, max_digits=8)),
                ('disbursement_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('payment_schedule', models.TextField(blank=True, default='')),
                ('purpose', models.TextField(blank=True, default='')),
                ('gl_account', models.CharField(default='343', max_length=20)),
                ('interest_account', models.CharField(default='635', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Dự thảo'), ('active', 'Đang vay'), ('closed', 'Đã tất toán'), ('defaulted', 'Quá hạn')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_loan',
                'ordering': ['-contract_date', '-id'],
                'unique_together': {('company', 'loan_no')},
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoanDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gl_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.accountingvoucher')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='loans.bankloan')),
            ],
            options={
                'db_table': 'loan_disbursement',
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('principal', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('interest', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gl_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.accountingvoucher')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.bankloan')),
            ],
            options={
                'db_table': 'loan_repayment',
            },
        ),
        migrations.CreateModel(
            name='LoanInterestAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('days', models.PositiveSmallIntegerField()),
                ('principal_base', models.DecimalField(decimal_places=4, max_digits=20)),
                ('interest_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gl_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.accountingvoucher')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_accruals', to='loans.bankloan')),
            ],
            options={
                'db_table': 'loan_interest_accrual',
                'unique_together': {('loan', 'period_year', 'period_month')},
            },
        ),
    ]
