# Generated by Django 5.2.15 on 2026-06-17 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('hr', '0001_initial'),
        ('ledger', '0002_accountperiodbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('fiscal_year', models.SmallIntegerField()),
                ('period_num', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Lưu tạm'), ('calculated', 'Đã tính'), ('posted', 'Đã ghi sổ'), ('paid', 'Đã trả lương')], default='draft', max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_insurance_employee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_insurance_employer', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_pit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_net', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='core.company')),
                ('gl_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='ledger.accountingvoucher')),
            ],
            options={
                'db_table': 'payroll_run',
                'ordering': ['-period'],
                'unique_together': {('company', 'period')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('late', 'Đi trễ'), ('early_leave', 'Về sớm'), ('absent', 'Vắng'), ('leave', 'Nghỉ phép'), ('holiday', 'Nghỉ lễ')], default='present', max_length=20)),
                ('work_days', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee')),
            ],
            options={
                'db_table': 'attendance_record',
                'ordering': ['-attendance_date'],
                'indexes': [models.Index(fields=['company', 'attendance_date'], name='attendance__company_18a89d_idx')],
                'unique_together': {('employee', 'attendance_date')},
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('work_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('base_salary', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('allowance_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('overtime_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('gross_salary', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('social_insurance_employee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('health_insurance_employee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('unemployment_insurance_employee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('social_insurance_employer', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('health_insurance_employer', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('unemployment_insurance_employer', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('pit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('net_salary', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='hr.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollrun')),
            ],
            options={
                'db_table': 'payroll_line',
                'ordering': ['line_no'],
                'unique_together': {('run', 'employee')},
            },
        ),
    ]
