# Generated by Django 5.2.15 on 2026-06-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollline',
            name='line_no',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
