# Generated by Django 5.2.15 on 2026-06-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payrollline_line_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollline',
            name='bhtnld_employer',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='kpcd_employer',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_bhtnld_employer',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_kpcd_employer',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
