# Generated by Django 5.2.15 on 2026-06-22 16:04

import apps.core.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_alter_taxrateconfig_pit_dependent_deduction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=255)),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('gl_account', models.CharField(default='1121', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'db_table': 'bank_account',
                'ordering': ['bank_name', 'account_number'],
                'unique_together': {('company', 'account_number')},
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='banking/imports/')),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('status', models.CharField(choices=[('uploaded', 'Đã tải lên'), ('parsed', 'Đã parse'), ('reconciled', 'Đã đối soát'), ('archived', 'Lưu trữ')], default='uploaded', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='banking.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_statement_import',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateField(db_index=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('debit', 'Bank debit (chi)'), ('credit', 'Bank credit (thu)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('counterparty_name', models.CharField(blank=True, default='', max_length=255)),
                ('counterparty_account', models.CharField(blank=True, default='', max_length=50)),
                ('counterparty_bank', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('is_reconciled', models.BooleanField(db_index=True, default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='core.company')),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankstatementimport')),
            ],
            options={
                'db_table': 'bank_transaction',
                'ordering': ['-txn_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('object_label', models.CharField(max_length=255)),
                ('object_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('match_method', models.CharField(choices=[('auto', 'Tự động'), ('manual', 'Thủ công')], default='auto', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='banking.banktransaction')),
            ],
            options={
                'db_table': 'bank_reconciliation_match',
            },
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['company', 'is_reconciled', '-txn_date'], name='bank_transa_company_15e6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account', '-txn_date'], name='bank_transa_bank_ac_6b7f3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reconciliationmatch',
            unique_together={('transaction', 'content_type', 'object_id')},
        ),
    ]
