# Generated by Django 5.2.15 on 2026-06-22 17:22

import apps.core.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_alter_taxrateconfig_pit_dependent_deduction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('scenario', models.CharField(choices=[('planned', 'Kế hoạch'), ('forecast', 'Dự phóng'), ('rolling', 'Cuộn (rolling)')], default='planned', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('total_revenue', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_expense', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_approved', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'db_table': 'budget',
                'ordering': ['-fiscal_year', 'scenario'],
                'unique_together': {('company', 'fiscal_year', 'scenario')},
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveSmallIntegerField()),
                ('account_group', models.CharField(max_length=50)),
                ('direction', models.CharField(default='debit', max_length=10)),
                ('planned_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('actual_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budget.budget')),
            ],
            options={
                'db_table': 'budget_line',
                'ordering': ['period_month', 'account_group'],
                'unique_together': {('budget', 'period_month', 'account_group', 'direction')},
            },
        ),
        migrations.CreateModel(
            name='CashFlowProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('expected_ar_collection', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('expected_ap_payment', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('expected_payroll', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('expected_tax', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('expected_other', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('opening_balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'db_table': 'cash_flow_projection',
                'unique_together': {('company', 'period_year', 'period_month')},
            },
            managers=[
                ('objects', apps.core.managers.CompanyManager()),
            ],
        ),
    ]
